const fs=require('node:fs'),path=require('node:path');const [root,input,out]=process.argv.slice(2),ref=path.join(root,'Scripts/native-render-parity/reference-source');
const v=fs.readFileSync(path.join(ref,'BrowserOverlayView.swift'),'utf8'),a=v.indexOf('    if(opacity===1&&appearance?.preserveSourceTextColor',v.indexOf('// One plate colour per lettering unit.')),b=v.indexOf('    // Display column groups.',a),body=v.slice(a,b);
const c=fs.readFileSync(path.join(ref,'BrowserSourceTextColor.swift'),'utf8'),x=c.indexOf('    const aidokuSourceColorLuminance ='),y=c.indexOf('    const aidokuLuminanceContrast',x),lum=c.slice(x,y);
const rect=r=>({left:r[0],top:r[1],right:r[0]+r[2],bottom:r[1]+r[3],width:r[2],height:r[3]});const css=rgb=>rgb?'rgb('+rgb.join(', ')+')':'transparent';const parse=s=>s==='transparent'?null:s.match(/[0-9.]+/g).map(Number).slice(0,3);
function run(j){
 const panels=j.members.map(m=>({dataset:{aidokuRegion:m.id,aidokuImageOcrOverlay:'source-readability-panel',...(m.glyphCover?{glyphCover:'true'}:{}),...(m.fills.length?{foreignFills:JSON.stringify(m.fills.map(f=>[...f.rect,css(f.color)]))}:{})},style:{backgroundColor:css(m.plate)},getBoundingClientRect:()=>rect(m.box),querySelectorAll:()=>Array(m.children??1).fill({})}));
 const nodes=j.members.map((m,i)=>({textContent:m.text,style:{visibility:m.visible===false?'hidden':'visible',color:css(m.fill),fontSize:String(m.font),webkitTextStrokeColor:css(m.stroke),webkitTextStrokeWidth:String(m.strokeWidth)},dataset:{aidokuRegion:m.id,sourceBackgroundColor:m.mode,sourceSampledTextRGB:m.source?.join(',')||'',outlinedLettering:JSON.stringify(m.ring??null),inkCluster:'old',finalInkCluster:'old'},parentElement:m.hasOwner===false?null:panels[i],ink:rect(m.ink)}));
 const others=j.neighbors.map(m=>({textContent:'foreign',dataset:{aidokuRegion:m.id},style:{visibility:m.visible===false?'hidden':'visible',color:css(m.fill)},ink:rect(m.ink)}));
 const root={dataset:{},querySelectorAll:q=>q.includes('source-readability-backing')?[]:q.includes('source-readability-panel')?panels:q.includes('"item"')?[...nodes,...others]:[]},items=j.members.map(m=>({id:m.id,sourceFontSize:m.glyph,vertical:m.vertical}));while(items.length<j.itemCount)items.push({id:'unused'+items.length});
 const appearance={preserveSourceTextColor:j.preserveText,preserveSourceBackgroundColor:j.preserveBackground},opacity=j.opacity,rotatedPlates=panels.filter((_,i)=>j.members[i].mode==='rotated-panel');
 const document={createRange:()=>({selectNodeContents(n){this.n=n},getBoundingClientRect(){return this.n.ink}})},getComputedStyle=n=>n.style,performance={now:()=>0};
 new Function('root','items','appearance','opacity','rotatedPlates','document','getComputedStyle','performance',lum+body)(root,items,appearance,opacity,rotatedPlates,document,getComputedStyle,performance);
 return{updates:nodes.filter(n=>n.dataset.letteringUnit).map(n=>({id:n.dataset.aidokuRegion,record:JSON.parse(n.dataset.letteringUnit),fill:parse(n.style.color),stroke:parse(n.style.webkitTextStrokeColor),width:parseFloat(n.style.webkitTextStrokeWidth),contrast:Number(n.dataset.sourceFinalMinimumContrast)})),panels:panels.map(p=>({id:p.dataset.aidokuRegion,color:parse(p.style.backgroundColor),fills:JSON.parse(p.dataset.foreignFills||'[]').map(f=>({rect:f.slice(0,4),color:parse(f[4])}))}))};
}
fs.writeFileSync(out,JSON.stringify(JSON.parse(fs.readFileSync(input,'utf8')).map(run)));
