#!/usr/bin/env python3
"""Generate checked buffer wrappers from the exact Rust C ABI (no kernel math here)."""
import re
from pathlib import Path
root = Path(__file__).resolve().parents[3]
functions = re.findall(r'pub unsafe extern "C" fn (\w+)\((.*?)\)(\s*->\s*\w+)?\s*\{',
                      (root / 'Scripts/overlay-kernels/kernels.rs').read_text(), re.S)
ct = {'u8':'uint8_t','i32':'int32_t','f32':'float','f64':'double'}
st = {'u8':'UInt8','i32':'Int32','f32':'Float','f64':'Double'}
capacities = {
 'lettering_rays': dict(rgba='n*4',dark='n',out='n*4'),
 'lettering_support':dict(rgba='n*4',out='4'),
 'glyph_index':dict(rgba='n*4',start='4097',order='n',cursor='4096'),
 'glyph_seed':dict(rgba='n*4',start='4097',order='n',mask='n',seen='n',queue='n',core='n',stats='5'),
 'glyph_enclosure':dict(rgba='n*4',core='Int(len)',out='2'),
 'stroke_glyph':dict(rgba='n*4',mask='n',seen='n',exterior='n',queue='n',core='n',heights='n',out='2'),
 'stroke_first':dict(rgba='n*4',core='Int(len)',sx='Int(len)',sy='Int(len)',first='Int(len)*8'),
 'stroke_seed':dict(rgba='n*4',sx='Int(samples)',sy='Int(samples)',first='Int(samples)*8',exterior='n',bands='Int(samples)*8',stats='15'),
 'bins_inside':dict(rgba='n*4',counts='4096',sums='12288',order='4096'),
 'transpose_rgba':dict(src='n*4',dst='n*4'),
 'outlined_components':dict(rgba='n*4',white='n',seen='n',queue='n',counts='4096',sums='12288',keys='4096',out='n*9'),
 'caption_mask':dict(rgba='n*4',near='n',mask='n',dots='n',halo='n',seen='n',queue='n',stats='4'),
 'caption_periodic':dict(dots='n'),
 'caption_exposed':dict(rgba='n*4',mask='n',halo='n',r='n',g='n',b='n',band='n',stats='3'),
 'columns_sort':dict(r='n',g='n',b='n',band='n',ro='n',go='n',bo='n',bando='n',offsets='767'),
 'columns_bins':dict(r='n',g='n',b='n',counts='4096',sums='12288',order='4096'),
 'columns_support':dict(r='n',g='n',b='n',out='4'),
 'columns_range':dict(r='n',g='n',b='n',hist='256'),
 'columns_brighter':dict(r='n',g='n',b='n',band='n',out='2'),
 'columns_sum':dict(r='n',g='n',b='n',out='3'),
 'harmonic_fill':dict(p='n*4',queue='Int(tail)',blocked='n',paint='n',work='n*3',links='Int(tail)'),
 'exemplar_fill':dict(rgba='n*4',mask='n',forbidden='n',fg='3',coeff='9',work='n*4',pending='n',residual='n*3',filled='n*3',integral='(Int(w)+1)*(Int(h)+1)',output='n*4',donors='n',cell='n',grid_x='Int(w)',grid_y='Int(h)',stats='7'),
 'enclosed_paper':dict(rgba='n*4',rects='(Int(aux_n)+Int(exc_n))*4',paper='n',seen='n',q='n',best='n',region='n',outside='n',points='n',meta='n*2',output='n*4',safe='n',stats='3'),
 'local_components':dict(rgba='n*4',bg='3',excluded='n',ink='n',seen='n',safe='n',q='n',paint='n',member='n',output='n*4',parts='Int(part_capacity)*8',points='n',stats='4'),
 'pixel_classes':dict(rgba='n*4',colors='12',raw='n',observed='n',protected='n'),
}
prelude = '''// Generated by Scripts/overlay-kernels/native/generate-bindings.py. Kernel algorithms live only in kernels.rs.
import Foundation
import AidokuOverlayKernels

protocol NativeKernelElement: AdditiveArithmetic {}
extension UInt8: NativeKernelElement {}
extension Int32: NativeKernelElement {}
extension Float: NativeKernelElement {}
extension Double: NativeKernelElement {}

/// Zeroed, aligned scratch owned for the entire native call; pointers never escape this bridge.
final class NativeKernelBuffer<Element: NativeKernelElement> {
    let count: Int
    fileprivate let pointer: UnsafeMutablePointer<Element>
    private let retainedOwner: AnyObject?
    private let ownsStorage: Bool
    fileprivate var byteCount: Int { max(1, count) * MemoryLayout<Element>.stride }
    init(count: Int) throws {
        guard count >= 0, count <= (128 * 1_024 * 1_024) / MemoryLayout<Element>.stride else {
            throw NativeTranslationPixelKernels.KernelError.invalidBuffer
        }
        self.count = count
        retainedOwner = nil
        ownsStorage = true
        pointer = .allocate(capacity: max(1, count))
        pointer.initialize(repeating: .zero, count: max(1, count))
    }
    convenience init(values: [Element]) throws {
        try self.init(count: values.count)
        if !values.isEmpty { values.withUnsafeBufferPointer { pointer.update(from: $0.baseAddress!, count: values.count) } }
    }
    private init(pointer: UnsafeMutablePointer<Element>, count: Int, owner: AnyObject) {
        self.pointer = pointer; self.count = count; retainedOwner = owner; ownsStorage = false
    }
    /// Native kernels intentionally alias byte/Float32 scratch. The view retains its source allocation;
    /// offset, alignment and full byte extent are validated, and borrowed storage is never freed twice.
    func view<Other: NativeKernelElement>(as: Other.Type, byteOffset: Int, count: Int) throws -> NativeKernelBuffer<Other> {
        let capacity = self.count * MemoryLayout<Element>.stride
        guard byteOffset >= 0, byteOffset <= capacity, count >= 0,
              count <= (capacity - byteOffset) / MemoryLayout<Other>.stride else {
            throw NativeTranslationPixelKernels.KernelError.invalidBuffer
        }
        let bytes = UnsafeMutableRawPointer(pointer).advanced(by: byteOffset)
        guard UInt(bitPattern: bytes) % UInt(MemoryLayout<Other>.alignment) == 0 else {
            throw NativeTranslationPixelKernels.KernelError.invalidBuffer
        }
        return NativeKernelBuffer<Other>(pointer: bytes.assumingMemoryBound(to: Other.self), count: count, owner: self)
    }
    deinit { if ownsStorage { pointer.deinitialize(count: max(1, count)); pointer.deallocate() } }
    var values: [Element] { Array(UnsafeBufferPointer(start: pointer, count: count)) }
    subscript(index: Int) -> Element {
        get { precondition((0..<count).contains(index)); return pointer[index] }
        set { precondition((0..<count).contains(index)); pointer[index] = newValue }
    }
    fileprivate func require(_ minimum: Int) throws {
        guard minimum >= 0, count >= minimum else { throw NativeTranslationPixelKernels.KernelError.invalidBuffer }
    }
}

enum NativeTranslationPixelKernels {
    enum KernelError: Error { case invalidGeometry, invalidBuffer, invalidIndex, invalidScalar }
    static let exportedKernelCount = 25
    private static func checkedCount(_ value: Int32) throws -> Int {
        guard value >= 0, value <= 4_000_000 else { throw KernelError.invalidGeometry }
        return Int(value)
    }
    private static func pixelCount(_ width: Int32, _ height: Int32) throws -> Int {
        guard width > 0, height > 0, width <= 16_384, height <= 16_384,
              Int64(width) * Int64(height) <= 4_000_000 else { throw KernelError.invalidGeometry }
        return Int(width) * Int(height)
    }
    private static func indices(_ buffer: NativeKernelBuffer<Int32>, count: Int, pixels: Int) throws {
        try buffer.require(count)
        for index in 0..<count where buffer[index] < 0 || Int(buffer[index]) >= pixels { throw KernelError.invalidIndex }
    }
    private static func finite(_ buffer: NativeKernelBuffer<Double>, count: Int) throws {
        try buffer.require(count)
        for index in 0..<count where !buffer[index].isFinite { throw KernelError.invalidScalar }
    }
'''
header = ['// Generated from kernels.rs. Compile the same Rust source for native CPU and WASM.','#pragma once','#include <stdint.h>', '#ifdef __cplusplus', 'extern "C" {', '#endif']
swift = [prelude]
for name, text, ret in functions:
    params=[]
    for item in text.split(','):
        label, typ = map(str.strip,item.split(':'))
        pointer = typ.startswith('*')
        base = typ.split()[-1] if pointer else typ
        params.append((label,typ,base,pointer))
    cparams = [f'{"const " if typ.startswith("*const") else ""}{ct[base]}{" *" if pointer else " "}{"aidoku_" + label}' for label,typ,base,pointer in params]
    header.append(f'{"int32_t" if ret.strip() else "void"} {name}({", ".join(cparams)});')
    sig = [f'{label}: NativeKernelBuffer<{st[base]}>' if pointer else f'{label}: {st[base]}' for label,typ,base,pointer in params]
    # Wrap lines deterministically for project line length policy.
    swift.append(f'    static func {name}(\n        '+',\n        '.join(sig)+f'\n    ) throws{ " -> Int32" if ret.strip() else ""} {{')
    labels={label for label,_,_,_ in params}
    if 'w' in labels and 'h' in labels: swift.append('        let n = try pixelCount(w, h)')
    elif name=='caption_exposed':
        swift.append('        guard w > 0, rgba.count % (Int(w)*4) == 0 else { throw KernelError.invalidGeometry }')
        swift.append('        let n = try pixelCount(w, Int32(rgba.count / (Int(w)*4)))')
    elif 'n' in labels: swift.append('        let n = try checkedCount(n)')
    elif 'count' in labels: swift.append('        let n = try checkedCount(count)')
    elif name=='columns_sum':
        swift.append('        guard from >= 0, to >= from else { throw KernelError.invalidGeometry }')
        swift.append('        let n = try checkedCount(to)')
    for label,typ,base,pointer in params:
        if not pointer and base=='f64': swift.append(f'        guard {label}.isFinite else {{ throw KernelError.invalidScalar }}')
    for label,typ,base,pointer in params:
        if not pointer and label in {'cr','cg','cb','fr','fg','fb','sr','sg','sb','ir','ig','ib','or','og','ob'}:
            swift.append(f'        guard {label} >= 0, {label} <= 255 else {{ throw KernelError.invalidScalar }}')
    for label,minimum in capacities[name].items(): swift.append(f'        try {label}.require({minimum})')
    if name in ['lettering_rays','caption_exposed']:
        height = 'h' if 'h' in labels else 'Int32(n / Int(w))'
        swift.append(f'        guard x0 >= 0, x1 >= x0, x1 <= w, y0 >= 0, y1 >= y0, y1 <= {height} else {{ throw KernelError.invalidGeometry }}')
    if name in ['glyph_enclosure','stroke_first']:
        swift.append('        guard len >= 0, stride > 0 else { throw KernelError.invalidScalar }')
        swift.append('        try indices(core, count: Int(len), pixels: n)')
    if name=='glyph_seed':
        swift.append('        guard start[0] == 0, start[4096] <= n else { throw KernelError.invalidIndex }')
        swift.append('        for index in 0..<4096 where start[index] < 0 || start[index] > start[index+1] { throw KernelError.invalidIndex }')
        swift.append('        try indices(order, count: Int(start[4096]), pixels: n)')
    if name=='stroke_seed':
        swift.append('        guard samples >= 0, samples <= n, reach > 0, reach <= 128 else { throw KernelError.invalidScalar }')
        swift.append('        for index in 0..<Int(samples) where sx[index] < 0 || sx[index] >= w || sy[index] < 0 || sy[index] >= h { throw KernelError.invalidIndex }')
        swift.append('        for index in 0..<(Int(samples)*8) where first[index] < 0 || first[index] > reach { throw KernelError.invalidIndex }')
    if name=='stroke_first':swift.append('        guard reach > 0, reach <= 128 else { throw KernelError.invalidScalar }')
    if name=='caption_mask':swift.append('        guard radius >= 0, radius <= 128, tolerance >= 0, tolerance <= 255 else { throw KernelError.invalidScalar }')
    if name=='caption_exposed':swift.append('        guard length > 0 else { throw KernelError.invalidScalar }')
    if name=='harmonic_fill':
        swift.append('        guard w > 2, n % Int(w) == 0, n / Int(w) > 2, tail >= 0, tail <= n else { throw KernelError.invalidGeometry }')
        swift.append('        try indices(queue, count: Int(tail), pixels: n)')
        swift.append('        for index in 0..<Int(tail) { let pixel = Int(queue[index]); guard pixel % Int(w) > 0, pixel % Int(w) < Int(w)-1, pixel >= Int(w), pixel < n-Int(w) else { throw KernelError.invalidIndex } }')
    if name=='exemplar_fill':
        swift.append('        guard erased >= 0, erased <= n else { throw KernelError.invalidScalar }')
        swift.append('        try finite(fg, count: 3); try finite(coeff, count: 9)')
    if name=='enclosed_paper':
        swift.append('        guard aux_n >= 0, exc_n >= 0, aux_n <= 4096, exc_n <= 4096, l >= 0, t >= 0, r >= l, r <= w, bottom >= t, bottom <= h else { throw KernelError.invalidGeometry }')
        swift.append('        try finite(rects, count: (Int(aux_n)+Int(exc_n))*4)')
    if name=='local_components':
        swift.append('        guard part_capacity >= 0, part_capacity <= n, l >= 0, t >= 0, right >= l, right <= w, bottom >= t, bottom <= h else { throw KernelError.invalidGeometry }')
        swift.append('        try finite(bg, count: 3)')
    if name=='pixel_classes':swift.append('        try finite(colors, count: 12)')
    buffers=[label for label,_,_,pointer in params if pointer]
    swift.append('        let scratch: [AnyObject] = ['+', '.join(buffers)+']')
    swift.append('        let byteCost = ['+', '.join(label+'.byteCount' for label in buffers)+'].reduce(0, +)')
    swift.append('        guard byteCost <= 512 * 1_024 * 1_024 else { throw KernelError.invalidBuffer }')
    args=[label+'.pointer' if pointer else ('Int32(n)' if label=='n' else label) for label,_,_,pointer in params]
    swift.append('        '+('return ' if ret.strip() else '')+'withExtendedLifetime(scratch) {')
    swift.append('            AidokuOverlayKernels.'+name+'(\n                '+',\n                '.join(args)+'\n            )')
    swift.append('        }\n    }\n')
swift.append('}\n')
header.extend(['#ifdef __cplusplus', '}', '#endif'])
(root/'Scripts/overlay-kernels/native/kernels.h').write_text('\n'.join(header)+'\n')
(root/'Scripts/overlay-kernels/native/module.modulemap').write_text('module AidokuOverlayKernels {\n    header "kernels.h"\n    export *\n}\n')
lines=[]
for line in '\n'.join(swift).splitlines():
    if len(line)>150 and ', ' in line:
        pieces=line.split(', ')
        current=pieces.pop(0)
        for piece in pieces:
            if len(current)+len(piece)+2>150:
                lines.append(current+',')
                current='            '+piece
            else: current+=', '+piece
        lines.append(current)
    elif len(line)>150 and '; ' in line:
        lines.extend(line.replace('; ', '\n            ').splitlines())
    else: lines.append(line)
(root/'Aidoku/Core/Translation/NativeEngine/Overlay/NativeTranslationPixelKernels.swift').write_text('\n'.join(lines)+'\n')
