// Generated from kernels.rs. Compile the same Rust source for native CPU and WASM.
#pragma once
#include <stdint.h>
#ifdef __cplusplus
extern "C" {
#endif
int32_t lettering_rays(const uint8_t *aidoku_rgba, uint8_t *aidoku_dark, int32_t aidoku_w, int32_t aidoku_h, int32_t aidoku_x0, int32_t aidoku_x1, int32_t aidoku_y0, int32_t aidoku_y1, int32_t *aidoku_out);
void lettering_support(const uint8_t *aidoku_rgba, int32_t aidoku_w, int32_t aidoku_h, double aidoku_l, double aidoku_r, double aidoku_t, double aidoku_b, int32_t aidoku_ir, int32_t aidoku_ig, int32_t aidoku_ib, int32_t *aidoku_out);
void glyph_index(const uint8_t *aidoku_rgba, int32_t aidoku_n, int32_t *aidoku_start, int32_t *aidoku_order, int32_t *aidoku_cursor);
int32_t glyph_seed(const uint8_t *aidoku_rgba, int32_t aidoku_w, int32_t aidoku_h, int32_t aidoku_cr, int32_t aidoku_cg, int32_t aidoku_cb, double aidoku_left, double aidoku_right, double aidoku_top, double aidoku_bottom, double aidoku_min_total, int32_t aidoku_vertical, double aidoku_origin, double aidoku_span, const int32_t *aidoku_start, const int32_t *aidoku_order, uint8_t *aidoku_mask, uint8_t *aidoku_seen, int32_t *aidoku_queue, int32_t *aidoku_core, int32_t *aidoku_stats);
void glyph_enclosure(const uint8_t *aidoku_rgba, int32_t aidoku_w, int32_t aidoku_h, const int32_t *aidoku_core, int32_t aidoku_len, int32_t aidoku_stride, int32_t aidoku_or, int32_t aidoku_og, int32_t aidoku_ob, int32_t *aidoku_out);
void stroke_glyph(const uint8_t *aidoku_rgba, int32_t aidoku_w, int32_t aidoku_h, int32_t aidoku_fr, int32_t aidoku_fg, int32_t aidoku_fb, double aidoku_left, double aidoku_right, double aidoku_top, double aidoku_bottom, uint8_t *aidoku_mask, uint8_t *aidoku_seen, uint8_t *aidoku_exterior, int32_t *aidoku_queue, int32_t *aidoku_core, int32_t *aidoku_heights, int32_t *aidoku_out);
int32_t stroke_first(const uint8_t *aidoku_rgba, int32_t aidoku_w, int32_t aidoku_h, const int32_t *aidoku_core, int32_t aidoku_len, int32_t aidoku_stride, int32_t aidoku_reach, int32_t aidoku_fr, int32_t aidoku_fg, int32_t aidoku_fb, int32_t *aidoku_sx, int32_t *aidoku_sy, int32_t *aidoku_first);
int32_t stroke_seed(const uint8_t *aidoku_rgba, int32_t aidoku_w, int32_t aidoku_h, int32_t aidoku_samples, const int32_t *aidoku_sx, const int32_t *aidoku_sy, const int32_t *aidoku_first, int32_t aidoku_reach, int32_t aidoku_fr, int32_t aidoku_fg, int32_t aidoku_fb, int32_t aidoku_sr, int32_t aidoku_sg, int32_t aidoku_sb, int32_t aidoku_rejoins, const uint8_t *aidoku_exterior, int32_t *aidoku_bands, int32_t *aidoku_stats);
int32_t bins_inside(const uint8_t *aidoku_rgba, int32_t aidoku_w, int32_t aidoku_h, double aidoku_left, double aidoku_right, double aidoku_top, double aidoku_bottom, int32_t aidoku_check_alpha, int32_t *aidoku_counts, int32_t *aidoku_sums, int32_t *aidoku_order);
void transpose_rgba(const uint8_t *aidoku_src, uint8_t *aidoku_dst, int32_t aidoku_w, int32_t aidoku_h);
int32_t outlined_components(const uint8_t *aidoku_rgba, int32_t aidoku_w, int32_t aidoku_h, int32_t aidoku_allow_dark, uint8_t *aidoku_white, uint8_t *aidoku_seen, int32_t *aidoku_queue, int32_t *aidoku_counts, int32_t *aidoku_sums, int32_t *aidoku_keys, int32_t *aidoku_out);
int32_t caption_mask(const uint8_t *aidoku_rgba, int32_t aidoku_w, int32_t aidoku_h, int32_t aidoku_ir, int32_t aidoku_ig, int32_t aidoku_ib, int32_t aidoku_tolerance, int32_t aidoku_radius, double aidoku_il, double aidoku_it, double aidoku_iright, double aidoku_ibottom, int32_t aidoku_dark_ink, double aidoku_interior_min, uint8_t *aidoku_near, uint8_t *aidoku_mask, uint8_t *aidoku_dots, uint8_t *aidoku_halo, uint8_t *aidoku_seen, int32_t *aidoku_queue, int32_t *aidoku_stats);
int32_t caption_periodic(const uint8_t *aidoku_dots, int32_t aidoku_w, int32_t aidoku_h, int32_t aidoku_axis);
void caption_exposed(const uint8_t *aidoku_rgba, int32_t aidoku_w, const uint8_t *aidoku_mask, const uint8_t *aidoku_halo, int32_t aidoku_textured, int32_t aidoku_x0, int32_t aidoku_x1, int32_t aidoku_y0, int32_t aidoku_y1, int32_t aidoku_vertical, double aidoku_start, double aidoku_length, uint8_t *aidoku_r, uint8_t *aidoku_g, uint8_t *aidoku_b, uint8_t *aidoku_band, int32_t *aidoku_stats);
void columns_sort(const uint8_t *aidoku_r, const uint8_t *aidoku_g, const uint8_t *aidoku_b, const uint8_t *aidoku_band, int32_t aidoku_count, uint8_t *aidoku_ro, uint8_t *aidoku_go, uint8_t *aidoku_bo, uint8_t *aidoku_bando, int32_t *aidoku_offsets);
int32_t columns_bins(const uint8_t *aidoku_r, const uint8_t *aidoku_g, const uint8_t *aidoku_b, int32_t aidoku_count, int32_t *aidoku_counts, int32_t *aidoku_sums, int32_t *aidoku_order);
void columns_support(const uint8_t *aidoku_r, const uint8_t *aidoku_g, const uint8_t *aidoku_b, int32_t aidoku_count, double aidoku_m0, double aidoku_m1, double aidoku_m2, int32_t *aidoku_out);
int32_t columns_range(const uint8_t *aidoku_r, const uint8_t *aidoku_g, const uint8_t *aidoku_b, int32_t aidoku_count, int32_t *aidoku_hist);
void columns_brighter(const uint8_t *aidoku_r, const uint8_t *aidoku_g, const uint8_t *aidoku_b, const uint8_t *aidoku_band, int32_t aidoku_count, double aidoku_m0, double aidoku_m1, double aidoku_m2, int32_t *aidoku_out);
void columns_sum(const uint8_t *aidoku_r, const uint8_t *aidoku_g, const uint8_t *aidoku_b, int32_t aidoku_from, int32_t aidoku_to, int32_t *aidoku_out);
void harmonic_fill(const uint8_t *aidoku_p, int32_t aidoku_w, int32_t aidoku_n, const int32_t *aidoku_queue, int32_t aidoku_tail, const uint8_t *aidoku_blocked, const uint8_t *aidoku_paint, int32_t aidoku_accelerated, float *aidoku_work, uint8_t *aidoku_links);
int32_t exemplar_fill(const uint8_t *aidoku_rgba, int32_t aidoku_w, int32_t aidoku_h, const uint8_t *aidoku_mask, const uint8_t *aidoku_forbidden, const double *aidoku_fg, const double *aidoku_coeff, int32_t aidoku_erased, uint8_t *aidoku_work, uint8_t *aidoku_pending, float *aidoku_residual, float *aidoku_filled, int32_t *aidoku_integral, uint8_t *aidoku_output, int32_t *aidoku_donors, double *aidoku_cell, int32_t *aidoku_grid_x, int32_t *aidoku_grid_y, double *aidoku_stats);
int32_t enclosed_paper(const uint8_t *aidoku_rgba, int32_t aidoku_w, int32_t aidoku_h, int32_t aidoku_l, int32_t aidoku_t, int32_t aidoku_r, int32_t aidoku_bottom, const double *aidoku_rects, int32_t aidoku_aux_n, int32_t aidoku_exc_n, uint8_t *aidoku_paper, uint8_t *aidoku_seen, int32_t *aidoku_q, int32_t *aidoku_best, uint8_t *aidoku_region, uint8_t *aidoku_outside, int32_t *aidoku_points, int32_t *aidoku_meta, uint8_t *aidoku_output, uint8_t *aidoku_safe, int32_t *aidoku_stats);
int32_t local_components(const uint8_t *aidoku_rgba, int32_t aidoku_w, int32_t aidoku_h, int32_t aidoku_l, int32_t aidoku_t, int32_t aidoku_right, int32_t aidoku_bottom, const double *aidoku_bg, double aidoku_bmax, const uint8_t *aidoku_excluded, uint8_t *aidoku_ink, uint8_t *aidoku_seen, uint8_t *aidoku_safe, int32_t *aidoku_q, uint8_t *aidoku_paint, uint8_t *aidoku_member, uint8_t *aidoku_output, int32_t *aidoku_parts, int32_t aidoku_part_capacity, int32_t *aidoku_points, int32_t *aidoku_stats);
void pixel_classes(const uint8_t *aidoku_rgba, int32_t aidoku_n, const double *aidoku_colors, int32_t aidoku_flags, double aidoku_ink_tolerance, double aidoku_halo_separation, uint8_t *aidoku_raw, uint8_t *aidoku_observed, uint8_t *aidoku_protected);
#ifdef __cplusplus
}
#endif
