const fs=require('fs'),vm=require('vm');const text=fs.readFileSync(process.argv[2],'utf8');let code=text.slice(text.indexOf('    // Final plate trim.'),text.indexOf('    // Final plate linkage.'));
// Instrument only page budget and source requests; original whole policy remains unchanged.
code=code.replace('root.dataset.finalPlateTrims=String(trimmedPlates);','root.dataset.finalPlateTrims=String(trimmedPlates); root.probeBudget=trimSamples;');
const inputs=JSON.parse(fs.readFileSync(process.argv[3],'utf8'));
const results=inputs.map(f=>{
 const flags=f.flags||{},calls=[];let currentPanel=[...f.plate],mutation=false,selected;
 const style=()=>{let target={left:f.plate[0]+'px',top:f.plate[1]+'px',width:f.plate[2]+'px',height:f.plate[3]+'px',transform:'none',clipPath:flags.clippedWithoutCoverage?'path(x)':'none',visibility:flags.hidden?'hidden':'visible',display:'block',backgroundImage:flags.hasBackgroundImage?'url(x)':'none',backgroundColor:`rgb(${f.plateRGB.join(',')})`};Object.defineProperty(target,'cssText',{get(){return JSON.stringify({...target})},set(v){Object.assign(target,JSON.parse(v))}});return target};
 const rect=a=>({left:a[0],top:a[1],right:a[0]+a[2],bottom:a[1]+a[3],width:a[2],height:a[3]});
 const node={dataset:{aidokuRegion:'one'},style:style(),scrollWidth:10,clientWidth:10,scrollHeight:10,clientHeight:10,getBoundingClientRect:()=>rect(f.ink)};
 node.style.fontSize=f.font+'px';if(f.foreground)node.dataset.sourceSampledTextRGB=f.foreground.join(',');if(f.outlined)node.dataset.outlinedLettering=JSON.stringify(f.outlined);if(flags.displayCardGrowth)node.dataset.displayCardGrowth='true';if(flags.captionTransformed)node.style.transform='rotate(1deg)';
 const panel={dataset:{aidokuRegion:'one'},style:style(),getBoundingClientRect:()=>rect(f.plate),querySelectorAll:()=>flags.otherChildren?[node,{}]:[node]};
 if(f.coverage)panel.dataset.panelCoverage=JSON.stringify(f.coverage);if(flags.sourceErasure)panel.dataset.sourceErasure='true';if(flags.sourcePreservedCaption)panel.dataset.sourcePreservedCaption='true';if(flags.transformed)panel.style.transform='rotate(1deg)';
 const otherNodes=(f.otherInks||[]).map((a,i)=>({dataset:{aidokuRegion:'other'+i},style:{visibility:'visible'},ink:a}));
 const root={dataset:{},querySelectorAll:q=>q.includes('"item"')?[node,...otherNodes]:q.includes('source-readability-backing')?(flags.hasBacking?[{dataset:{aidokuRegion:'one'}}]:[]):[panel]};panel.parentElement=root;node.parentElement=panel;
 const item={id:'one',sourceBounds:f.bounds,auxiliaryInkRects:f.auxiliary||[],sourceFontSize:f.sourceFont,sourceVertical:f.vertical,rotation:f.rotation||0};
 const restore=f.restoration?{canvas:{isConnected:true,style:{visibility:'visible',display:'block'},getBoundingClientRect:()=>rect(f.restoration)}}:null;
 const sandbox={root,items:[item,...f.others.map(o=>({id:o.id,sourceBounds:o.bounds,sourceFontSize:o.font,sourceVertical:o.vertical,auxiliaryInkRects:o.auxiliary||[]}))],opacity:f.opacity??1,appearance:{preserveSourceBackgroundColor:true},cleanupImageGeometry:{frame:f.frame},sourceImage:{complete:f.imageComplete??true,naturalWidth:f.width,naturalHeight:f.height},cachedSourceSample:()=>f.sample||{},restoredPanelGeometry:new Map(restore?[[item,restore]]:[]),performance:{now:()=>0},scrollX:0,scrollY:0,CSS:{supports:()=>f.validation.clipSupported??true},getComputedStyle:o=>o.style,document:{createElement:()=>({getContext:()=>({})}),createRange:()=>({selectNodeContents:n=>{selected=n},getBoundingClientRect:()=>{if(selected!==node)return rect(selected.ink);const r=rect(f.ink);if(panel.style.left!==f.plate[0]+'px'){for(const k of ['left','right','top','bottom'])r[k]+=f.validation.shift||0;if(f.validation.fits===false)node.scrollWidth=20;}return r}})},sourcePixelReader:{read:(ctx,x,y,w,h)=>{calls.push([x,y,w,h]);if(f.throwRead)throw Error('read');let out=new Uint8ClampedArray(w*h*4);for(let yy=0;yy<h;yy++)for(let xx=0;xx<w;xx++)for(let c=0;c<4;c++)out[(yy*w+xx)*4+c]=f.rgba[((y+yy)*f.width+x+xx)*4+c];return out}}};
 let run=code;if(f.budget!==undefined)run=run.replace('trimSamples=1048576','trimSamples='+f.budget);vm.runInNewContext(run,sandbox);
 const accepted=!!panel.dataset.finalPlateTrim;return {id:f.id,result:accepted?{rect:['left','top','width','height'].map(k=>parseFloat(panel.style[k])),coverage:panel.dataset.panelCoverage?JSON.parse(panel.dataset.panelCoverage):null,clipped:!!(panel.style.clipPath&&panel.style.clipPath!=='none'),areas:JSON.parse(panel.dataset.finalPlateTrim)}:null,budget:root.probeBudget??(f.budget??1048576),calls,error:root.dataset.finalPlateTrimError||null};
});fs.writeFileSync(process.argv[4],JSON.stringify(results));
