/*
 * Copyright (C) 2023 Apple Inc. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY APPLE INC. AND ITS CONTRIBUTORS ``AS IS''
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
 * THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 * PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL APPLE INC. OR ITS CONTRIBUTORS
 * BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
 * THE POSSIBILITY OF SUCH DAMAGE.
 */

import Foundation
import CoreFoundation

/// Primary WebKit normal line-break fast paths with the public neutral CF
/// line-break iterator as mechanical backend. This backend is validated against
/// bounded actual WK captures, not claimed equivalent for all Unicode scripts.
enum NativeNormalBreakOpportunities {
    typealias Item = NativeKeepAllBreakOpportunities.Item
    typealias Analysis = NativeKeepAllBreakOpportunities.Analysis
    private static let al = 1, id = 2, cm = 4, op = 8, cp = 16, cl = 32
    private static let gl = 64, qu = 128, sp = 256, weird = 32768

    static func analyze(text: String) -> Analysis? {
        let units = Array(text.utf16)
        guard !units.isEmpty, units.count <= 8192,
              !units.contains(9), !units.contains(10), !units.contains(13), !units.contains(0x00AD),
              !hasUnsupportedBidi(text) else { return nil }
        let value = text as CFString
        let locale = CFLocaleCreate(nil, CFLocaleIdentifier("und" as CFString))
        let iterator = CFStringTokenizerCreate(nil, value, CFRange(location: 0, length: units.count),
                                               kCFStringTokenizerUnitLineBreak, locale)
        var backendEnds: [Int] = []
        while CFStringTokenizerAdvanceToNextToken(iterator).rawValue != 0 {
            let range = CFStringTokenizerGetCurrentTokenRange(iterator)
            backendEnds.append(range.location + range.length)
        }
        var items: [Item] = [], position = 0
        while position < units.count {
            let start = position
            if units[position] == 32 {
                repeat { position += 1 } while position < units.count && units[position] == 32
                items.append(.init(range: NSRange(location: start, length: position - start), kind: .whitespace))
            } else {
                var probe = start
                repeat {
                    let end = next(units, start: probe, backendEnds: backendEnds)
                    if end != start { position = end; break }
                    probe += 1
                } while probe < units.count
                if position == start { position = units.count }
                items.append(.init(range: NSRange(location: start, length: position - start), kind: .text))
            }
            guard position > start, items.count <= 512 else { return nil }
        }
        return Analysis(items: items, paragraphs: [.init(range: NSRange(location: 0, length: units.count),
            softOffsets: items.map { NSMaxRange($0.range) })], hasPreservedTab: false, hasSoftHyphen: false)
    }

    /// Conservative single-LTR-node scope; callers retain their established
    /// fallback for RTL scripts and embedding/isolate controls.
    static func hasUnsupportedBidi(_ text: String) -> Bool {
        text.unicodeScalars.contains { scalar in
            let v = scalar.value
            return (0x0590...0x08FF).contains(v) || (0xFB1D...0xFDFF).contains(v) ||
                (0xFE70...0xFEFF).contains(v) || (0x10800...0x10FFF).contains(v) ||
                (0x1E800...0x1EEFF).contains(v) || (0x202A...0x202E).contains(v) ||
                (0x2066...0x2069).contains(v)
        }
    }
    private static func space(_ c: UInt16) -> Bool { c == 32 || c == 9 || c == 10 }
    private static func asciiAlpha(_ c: UInt16) -> Bool { (65...90).contains(c) || (97...122).contains(c) }
    private static func asciiDigit(_ c: UInt16) -> Bool { (48...57).contains(c) }

    private static func next(_ u: [UInt16], start: Int, backendEnds: [Int]) -> Int {
        var i = start
        if i == 0 { if u.count <= 1 { return u.count }; i += 1 }
        var beforeBefore: UInt16 = i > 1 ? u[i - 2] : 0
        var before: UInt16 = i > 0 ? u[i - 1] : 0
        var beforeType = 0
        var nextBreak: Int?
        while i < u.count {
            let after = u[i]
            var afterType = 0
            defer { beforeBefore = before; before = after; beforeType = afterType; i += 1 }
            if space(after) { return i }
            if before == 45 && asciiDigit(after) {
                if asciiAlpha(beforeBefore) || asciiDigit(beforeBefore) { return i }
                continue
            }
            if before <= 255 && after <= 255 {
                if before >= 33 && after >= 33 {
                    let row = Int(before) - 33, column = Int(after) - 33
                    if latin1[row * 28 + column / 8] & (1 << (column % 8)) != 0 { return i }
                }
                continue
            }
            if beforeType == 0 { beforeType = classify(before) }
            afterType = classify(after)
            let pair = beforeType | afterType
            if pair & ~(sp | al | qu) == 0 { continue }
            if pair | al == id | al { return i }
            if pair & (gl | qu) != 0 && pair & weird == 0 { continue }
            if afterType == cm { afterType = beforeType; continue }
            if pair & weird == 0 && pair & (cl | cp | op) != 0 {
                if afterType == cl || afterType == cp || beforeType == op { continue }
                if pair & id != 0 { return i }
            }
            if nextBreak == nil || nextBreak! < i { nextBreak = backendEnds.first { $0 > i - 1 } }
            if let end = nextBreak, i < end {
                let maximum = min(end, u.count - 1)
                while i < maximum {
                    let lookahead = u[i + 1]
                    if lookahead <= 255 && !asciiAlpha(lookahead) { break }
                    // Preserve the literal primary fast-forward state updates.
                    beforeBefore = before; before = after; beforeType = afterType; i += 1
                }
            }
            if i == nextBreak && !space(before) { return i }
        }
        return u.count
    }

    static func classify(_ c: UInt16) -> Int {
        switch Int(c) / 128 {
        case 0:
            switch Int(c) / 16 {
            case 0: return weird
            case 1: return cm
            case 2:
                if c == 32 { return sp }; if c == 34 || c == 39 { return qu }
                if c == 40 { return op }; if c == 41 { return cp }; return weird
            case 3: return c <= 57 ? al : weird
            case 4, 6: return al
            case 5:
                if c <= 90 { return al }; if c == 91 { return op }; if c == 93 { return cp }; return weird
            case 7:
                if c <= 122 { return al }; if c == 123 { return op }; if c == 125 { return cl }; return weird
            default: return weird
            }
        case 1:
            if c == 160 { return gl }; if c > 192 { return al }
            if c == 161 || c == 191 { return op }; if c == 171 || c == 187 { return qu }; return weird
        case 2, 3, 4: return al
        case 5: return c == 0x02C8 || c == 0x02CC || c == 0x02DF ? weird : al
        case 6:
            if c == 0x034F || (0x035C...0x0362).contains(c) { return gl }
            if c < 0x370 { return cm }; return c == 0x037E ? weird : al
        case 7, 8: return al
        case 9: return (0x0483...0x0489).contains(c) ? cm : al
        case 10: return al
        case 11:
            if c <= 0x0588 || c >= 0x05C8 { return al }
            if (0x0591...0x05BD).contains(c) { return cm }
            return [0x05BF,0x05C1,0x05C2,0x05C4,0x05C5,0x05C7].contains(Int(c)) ? cm : weird
        case 12...19, 32...51: return weird
        case 64: return c == 0x2018 || c == 0x2019 ? qu : weird
        default: break
        }
        if (0x2E80...0xA4CF).contains(c) {
            if c & 0xFF00 == 0x3000 {
                if c <= 0x303F {
                    switch c & 0x1F {
                    case 1,2,9,11,13,15,17,21,23,25,27,30,31: return cl
                    case 8,10,12,14,16,22,20,24,26,29: return op
                    default: return weird
                    }
                }
                return weird
            }
            if c & 0xFFF0 == 0x31F0 { return weird }
            if c & 0xFFF8 == 0x3248 || c & 0xFFC0 == 0x4DC0 { return al }
            if c == 0xA015 { return weird }; return id
        }
        if (0xAC00...0xD7AF).contains(c) || (0xF900...0xFAFF).contains(c) { return id }
        return weird
    }
    // Primary generated Latin1 compatibility table (223 rows × 28 bytes).
    private static let latin1 = Array(Data(base64Encoded: "gAAACAAAAAQAAAAEAAAAAP/r//v/////////f4AAAAgAAAAEAAAABAAAAAAAAAAAAAAAAAAAAACAAAAIAAAABAAAAAQAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB+ACUAAAAAAAAAAAIAAAAgAAAAEAAAABAAAAAAfgAlAAAAAAAAAAACAAAAIAAAABAAAAAQAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAIAAAABAAAAAQAAAAAH4AJQAAAAAAAAAAAgAAACAAAAAQAAAAEAAAAAAAACAAAAAAAAAAAAIAAAAgAAAAEAAAABAAAAAAfgAlAAAAAAAAAAACAAAAIAAAABAAAAAQAAAAAH4AJQAAAAAAAAAAA/1cA/v////////9/AAAAgB+ACUAAAAAAAAAAAIAAAAgAAAAEAAAABAAAAAAfgAlAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/+v/+/////////9/AAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAIAAAAgAAAAEAAAABAAAAAAfgAlAAAAAAAAAAACAAAAIAAAABAAAAAQAAAAAH4AJQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAIAAAAgAAAAEAAAABAAAAAAAAAgAAAAAAAAAAACAAAAIAAAABAAAAAQAAAAAAAAIAAAAAAAAAAAAvJb/uf///+////9vAAAAAP/r//v/////////fwAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAIAAAABAAAAAQAAAAAH4AJQAAAAAAAAAAAgAAACAAAAAQAAAAEAAAAAB+ACUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAgAAAAEAAAABAAAAID/6//7/////////3+AAAAIAAAABAAAAAQAAAAA/+v/+/////////9/gAAACAAAAAQAAAAEAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAP///////////////////////////////////38AAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAmAQAAAAAAAwAAAAEAAAAAB+ACUAAAAAAAAAAAJgEAAAAAAAMAAAABAAAAAAfgAlAAAAAAAAAAACYBAAAAAAADAAAAAQAAAAAH4AJQAAAAAAAAAAAmAQAAAAAAAwAAAAEAAAAAB+ACUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAC8hv+5////7////ycAAACA/+v/+/////////9/AAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAACYBAAAAAAADAAAAAQAAAAAH4AJQAAAAAAAAAAAmAQAAAAAAAwAAAAEAAAAAB+ACUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAA==")!)
}
