const fs=require('fs'),path=require('path');const root=process.argv[2],output=process.argv[3],ref=path.join(root,'Scripts/native-render-parity/reference-source');
const view=fs.readFileSync(path.join(ref,'BrowserOverlayView.swift'),'utf8'),typo=fs.readFileSync(path.join(ref,'BrowserOverlayTypography.swift'),'utf8');
function extract(text,name){const start=text.indexOf('const '+name+' ='),begin=text.indexOf('{',start);let depth=0,end=begin;for(;end<text.length;end++){if(text[end]==='{')depth++;if(text[end]==='}'&&--depth===0)break;}return text.slice(start,end+2);}
const policies=['aidokuHasResidualLettering','aidokuRestoredErasureCovers'].map(n=>extract(typo,n)).concat(['aidokuFillEnclosedSpecks','aidokuHiddenForeignRepaint','aidokuMainbodyCellsClear'].map(n=>extract(view,n))).join('\n');
const shortStart=view.indexOf('    if(inpaintingEnabled&&opacity===1){',view.indexOf('// Short captions need only a glyph outline after local background repair.'));
const shortEnd=view.indexOf('    // A failed or budget-skipped local restoration',shortStart),shortCode=view.slice(shortStart,shortEnd);
const balloonStart=view.indexOf('        const item=items.find(item=>item.id===entry.id),id=String(entry.id),c=item&&restoredPanelGeometry.get(item);');
const balloonEnd=view.indexOf('\n      }})();} finally',balloonStart),balloonCode='for(const entry of [entryFixture]){\n'+view.slice(balloonStart,balloonEnd)+'\n}';
const snapshot=(c)=>({rgba:Array.from(c.image.data),safe:Array.from(c.safe),luminance:Array.from(c.luminance),revision:c.surfaceRevision??0,enclosedSpecks:c.enclosedSpecks??null,coreClear:c.coreClear??null,innerCoreClear:c.innerCoreClear??null,residualLettering:c.residualLettering??null});
const box=r=>({left:r[0],top:r[1],right:r[0]+r[2],bottom:r[1]+r[3],width:r[2],height:r[3]});
const run=new Function('f','snapshot','box',policies+`
 const trace=[],c={w:f.w,h:f.h,iw:f.imageSize[0],ih:f.imageSize[1],frame:f.frame,x:f.crop[0],y:f.crop[1],sx:f.scale[0],sy:f.scale[1],erasureComplete:f.erasureComplete,partialErasureCertified:f.partial,provisional:f.provisional,sourceRemainingInk:f.remaining,safe:new Uint8Array(f.safe),luminance:new Uint8Array(f.luminance),surfaceRevision:f.revision,coreClear:f.coreClear,innerCoreClear:f.innerCoreClear,residualLettering:true,image:{data:new Uint8ClampedArray(f.rgba)}};
 c.canvas={width:f.w,height:f.h,isConnected:f.canvasConnected,dataset:{localRestorationProposal:f.localProposal?'true':''},style:{visibility:f.canvasHidden?'hidden':''},getContext:()=>({getImageData:()=>c.image,putImageData:()=>{}}),remove:()=>{trace.push('detach');c.canvas.isConnected=false;}};
 const item={id:'A',sourceBounds:f.sourceBounds,sourceFrame:f.frame,sourceFontSize:f.sourceFont,auxiliaryInkRects:f.aux,rotation:f.rotation,balancedColumn:f.balanced,sourceSingleColumn:f.single,text:f.text};
 const plate={isConnected:f.plateConnected,dataset:{aidokuRegion:'A'},getBoundingClientRect:()=>box(f.plate),remove:()=>{plate.isConnected=false;},insertBefore:()=>{trace.push('restore');node.parentNode=plate;}};
 const backing={dataset:{aidokuRegion:'A'},remove:()=>trace.push('remove-backing')};
 const root={contains:()=>f.canvasOwned,appendChild:o=>{if(o===c.canvas){trace.push('attach');o.isConnected=true;}else{trace.push('lift');o.parentNode=root;}},querySelector:()=>f.nodePresent?node:null,querySelectorAll:selector=>selector.includes('source-readability-backing')?[backing]:selector.includes('source-readability-panel')?Array(f.plateCount).fill(plate):[]};
 const node={parentNode:f.parent==='root'?root:f.parent==='plate'?plate:{},nextSibling:null,style:{visibility:f.nodeHidden?'hidden':'',scale:f.nodeScaled?'2':'',fontSize:String(f.font),cssText:'original'},dataset:{sourceErasureRestored:f.certified?'true':''},getBoundingClientRect:()=>box(f.nodeRect)};
 const items=[item,...f.otherRects.map((r,k)=>({id:'other'+k,sourceFrame:[0,0,1,1],sourceBounds:r}))],restoredPanelGeometry=new Map([[item,c]]),restoredSourcePanels=new Set(f.alreadyReleased?[item]:[]);
 let searches=f.searches,lateFits=0,balloonSafeFitBudget=f.budget?1:0,scrollX=0,scrollY=0;
 const eligible=()=>{trace.push('eligible');return aidokuRestoredErasureCovers(c.safe,c.w,c.h,f.regions,f.glyph,f.core);};
 const entryFixture={id:'A',restorationFitEligible:eligible,completeResidualErasure:()=>{trace.push('residual');if(!f.residualAllowed)return null;const previous=snapshot(c);for(const i of f.residualIndices){c.safe[i]=1;c.luminance[i]=255;c.image.data.set([255,255,255,255],i*4);}c.surfaceRevision++;node.dataset.sourceResidualFilled=String(f.residualFilled);return()=>{trace.push('undo-residual');const rev=c.surfaceRevision+1;c.safe=new Uint8Array(previous.safe);c.luminance=new Uint8Array(previous.luminance);c.image.data.set(previous.rgba);c.surfaceRevision=rev;c.coreClear=previous.coreClear;c.innerCoreClear=previous.innerCoreClear;c.residualLettering=previous.residualLettering;};},fitBalloon:()=>{trace.push('fit');return !f.fitFails&&aidokuMainbodyCellsClear(c.safe,c.w,c.h,f.glyphRects);},commitRestorationFit:()=>trace.push('commit')};
 const captionNodes=new Map(f.nodePresent?[['A',node]]:[]),cards=new Map([['A',plate]]),residualFillKey=()=>f.refused?'refused':'fresh';c.residualRefused=f.refused?'refused':'different';
 const inpaintingEnabled=f.inpainting,opacity=f.opacity;
 if(f.op==='short'){${shortCode}
 return {surface:snapshot(c),outcome:{accepted:node.dataset.smallCaptionInpainted==='true',unsafe:node.dataset.smallRestorationUnsafe===undefined?null:Number(node.dataset.smallRestorationUnsafe),strokeWidth:node.dataset.smallCaptionInpainted==='true'?Number(node.style.webkitTextStrokeWidth.slice(0,-2)):null,enclosedSpecks:node.dataset.smallCaptionInpainted==='true'?(c.enclosedSpecks??null):null}};}
 ${balloonCode}
 return {surface:snapshot(c),outcome:{accepted:lateFits===1,searched:searches>f.searches,enclosedSpecks:lateFits===1?(c.enclosedSpecks??null):null,localProposalCommitted:node.dataset.localRestorationCommitted==='true'},trace,searches,successfulFits:lateFits,canvasConnected:c.canvas.isConnected,provisional:c.provisional};
`);
const rows=[];function make(name,op='short',mutate=()=>{}){const w=40,h=32;let f={name,op,w,h,imageSize:[40,32],frame:[0,0,40,32],crop:[0,0],scale:[1,1],sourceBounds:[.25,.25,.5,.5],sourceFont:8,aux:[],erasureComplete:true,partial:false,provisional:false,localProposal:false,canvasConnected:true,canvasOwned:true,canvasHidden:false,remaining:0,safe:Array(w*h).fill(1),luminance:Array(w*h).fill(100),rgba:Array.from({length:w*h},()=>[200,211,222,255]).flat(),revision:7,coreClear:true,innerCoreClear:false,text:'짧은 글',single:true,rotation:0,balanced:false,plateConnected:true,nodePresent:true,nodeHidden:false,nodeScaled:false,parent:'root',plateCount:1,plate:[10,8,20,16],nodeRect:[12,10,16,12],font:10,inpainting:true,opacity:1,otherRects:[],searches:0,budget:true,alreadyReleased:false,certified:false,regions:[[10,8,20,16]],core:[[10,8,20,16]],glyph:8,glyphRects:[[12,12,8,8]],residualAllowed:false,residualIndices:[],residualFilled:0,fitFails:false,refused:false};if(op==='balloon')f.sourceBounds=[0,0,1,1];mutate(f);rows.push(f);}
function hole(f,x,y){let i=y*f.w+x;f.safe[i]=0;f.rgba.splice(i*4,4,10,20,30,60);return i;}
make('short-clear');make('short-enclosed-speck','short',f=>hole(f,15,13));make('short-five-island-rejected','short',f=>{for(let x=14;x<19;x++)hole(f,x,13);});make('short-flat-speck-then-large-island-undo','short',f=>{hole(f,12,10);for(let x=20;x<25;x++)hole(f,x,18);});make('short-alpha-ring-retains-island','short',f=>{hole(f,15,13);f.rgba[(12*40+14)*4+3]=100;});make('short-edge-art-retained','short',f=>{for(let y=0;y<16;y++)hole(f,10,y);});make('short-too-much-edge-art','short',f=>{for(let y=0;y<32;y++)for(let x=10;x<14;x++)hole(f,x,y);});
for(const [name,key,value] of [['partial','partial',true],['provisional','provisional',true],['rotation','rotation',3],['not-single','single',false],['long-text','text','1234567890123'],['remaining-too-high','remaining',9],['missing-remaining','remaining',null],['canvas-detached','canvasConnected',false],['missing-node','nodePresent',false],['two-plates','plateCount',2],['wrong-parent','parent','other'],['opacity','opacity',.8],['disabled','inpainting',false],['erasure-incomplete','erasureComplete',false]])make('short-'+name,'short',f=>f[key]=value);
make('short-touching-neighbor','short',f=>f.otherRects=[[30,8,2,16]]);make('short-overlap-neighbor','short',f=>f.otherRects=[[29.5,8,2,16]]);make('short-aux-rejected','short',f=>f.aux=[[.1,.1,.1,.1]]);make('short-unicode-codepoints','short',f=>f.text='👩‍👩‍👧‍👦👩‍👩‍👧‍👦');make('short-plate-parent','short',f=>f.parent='plate');
make('balloon-clear','balloon');make('balloon-speck-commit','balloon',f=>hole(f,15,13));make('balloon-speck-fit-rejected-undo','balloon',f=>{hole(f,15,13);f.fitFails=true;});make('balloon-plate-lift-rollback','balloon',f=>{f.parent='plate';f.fitFails=true;});make('balloon-detached-proposal-commit','balloon',f=>{f.provisional=true;f.localProposal=true;f.canvasConnected=false;});make('balloon-detached-proposal-rollback','balloon',f=>{f.provisional=true;f.localProposal=true;f.canvasConnected=false;f.fitFails=true;hole(f,15,13);});make('balloon-foreign-repaint-veto','balloon',f=>f.sourceBounds=[.4,.4,.1,.1]);
for(const [name,key,value] of [['budget','budget',false],['search-limit','searches',3],['partial','partial',true],['incomplete','erasureComplete',false],['provisional-connected','provisional',true],['canvas-detached','canvasConnected',false],['canvas-unowned','canvasOwned',false],['canvas-hidden','canvasHidden',true],['released','alreadyReleased',true],['rotation','rotation',8],['balanced','balanced',true],['missing-node','nodePresent',false],['missing-plate','plateConnected',false],['hidden-node','nodeHidden',true],['scaled-node','nodeScaled',true],['wrong-parent','parent','other']])make('balloon-'+name,'balloon',f=>f[key]=value);
function residual(f){for(let x=14;x<19;x++)f.residualIndices.push(hole(f,x,13));f.residualAllowed=true;f.residualFilled=5;}
make('balloon-residual-commit','balloon',residual);make('balloon-residual-fit-reject-undo','balloon',f=>{residual(f);f.fitFails=true;});make('balloon-residual-quarter-glyph-veto','balloon',f=>{residual(f);f.residualFilled=25;});make('balloon-residual-refused','balloon',f=>{residual(f);f.refused=true;});make('balloon-no-core-proof-veto','balloon',f=>{residual(f);f.coreClear=false;});make('balloon-certified-skip-residual','balloon',f=>{residual(f);f.certified=true;});make('balloon-residual-plus-speck-undo','balloon',f=>{residual(f);hole(f,21,19);f.fitFails=true;});
for(const f of rows)f.expected=run(f,snapshot,box);fs.writeFileSync(output,JSON.stringify(rows));console.log(rows.length+' exact frozen trials');
