const fs=require('fs'),path=require('path');const root=process.argv[2],out=process.argv[3],ref=path.join(root,'Scripts/native-render-parity/reference-source');const view=fs.readFileSync(path.join(ref,'BrowserOverlayView.swift'),'utf8'),typo=fs.readFileSync(path.join(ref,'BrowserOverlayTypography.swift'),'utf8');
function extract(text,name){const start=text.indexOf('const '+name+' ='),begin=text.indexOf('{',start);let depth=0,end=begin;for(;end<text.length;end++){if(text[end]==='{')depth++;if(text[end]==='}'&&--depth===0)break;}return text.slice(start,end+2);}
const policies=['aidokuHasResidualLettering','aidokuHasAttachedLeadingInk','aidokuRestoredErasureCovers'].map(n=>extract(typo,n)).join('\n');
const start=view.indexOf('          const old=rect(panel.getBoundingClientRect());',view.indexOf('let certificationBudget=524288;')),mid=view.indexOf('          const glyphMaskProof=',start),end=view.indexOf('          certifiedErasure.add(item);',mid);
const groupStart=view.indexOf('          if(item.sourceVertical&&!item.sourceSingleColumn&&aidokuHasAttachedLeadingInk(safe,c.w,c.h,core,glyph))continue;',end),groupEnd=view.indexOf('          c.groupErasureCertified=true;',groupStart);
const run=new Function('q',policies+`
const item={sourceBounds:q.sourceBounds,auxiliaryInkRects:q.aux,sourceFontSize:q.font,sourceVertical:q.vertical,sourceSingleColumn:q.single};const c={w:q.w,h:q.h,iw:q.imageSize[0],ih:q.imageSize[1],frame:q.frame,x:q.crop[0],y:q.crop[1],sx:q.scale[0],sy:q.scale[1],safe:new Uint8Array(q.safe),sourceErasureVerified:q.verified,method:q.method,sourceGlyphsVerified:q.glyphsVerified};const f=q.sourceFrame,px=q.padding[0],py=q.padding[1],node={style:{fontSize:String(q.displayFont)}},panel={getBoundingClientRect:()=>q.plate},rect=x=>x,id='A',erasureRetries=[];let certificationBudget=524288,accepted=false,geometry=null;
for(const unused of [0]){${view.slice(start,mid)}
geometry={viewportRects:coverage,regions,core,glyphSize:glyph};
if(q.group){const safe=c.safe;${view.slice(groupStart,groupEnd)}}else{${view.slice(mid,end)}}
accepted=true;}
return {accepted,geometry};`);
const rows=[];function make(name,mutate=()=>{}){const w=40,h=32;let f={name,w,h,imageSize:[w,h],sourceFrame:[2,3,80,64],frame:[2,3,80,64],crop:[0,0],scale:[1,1],sourceBounds:[.25,.25,.5,.5],aux:[],font:8,displayFont:10,padding:[3,4],plate:[19.5,17.5,45,38],vertical:false,single:true,verified:false,method:null,glyphsVerified:false,group:false,safe:Array(w*h).fill(1)};mutate(f);rows.push(f);}
function hole(f,x,y){f.safe[y*f.w+x]=0;}
make('margin-clean');make('margin-group-clean',f=>f.group=true);make('margin-source-singleton-veto',f=>hole(f,15,13));make('margin-source-singleton-verified',f=>{hole(f,15,13);f.verified=true;});make('margin-source-diagonal-veto',f=>{hole(f,15,13);hole(f,16,14);f.verified=true;});make('margin-chromatic-initial-exempt',f=>{hole(f,15,13);hole(f,16,14);f.verified=true;f.method='chromatic-balloon-glyphs';f.glyphsVerified=true;});make('margin-chromatic-group-recheck',f=>{hole(f,15,13);hole(f,16,14);f.verified=true;f.method='chromatic-balloon-glyphs';f.glyphsVerified=true;f.group=true;});make('margin-wide-rule-core-veto',f=>{for(let x=0;x<40;x++)hole(f,x,13);});make('margin-wide-rule-verified',f=>{for(let x=0;x<40;x++)hole(f,x,13);f.verified=true;});make('margin-malformed-bounds',f=>f.sourceBounds=[1,2,3]);make('margin-zero-bounds',f=>f.sourceBounds=[.2,.2,0,.5]);make('margin-negative-bounds',f=>f.aux=[[.1,.1,-.2,.3]]);make('margin-auxiliary',f=>f.aux=[[.1,.1,.12,.13],[.8,.75,.15,.15]]);make('margin-empty-coverage',f=>f.plate=[-30,-30,4,5]);make('margin-zero-font-fallback',f=>f.font=0);make('margin-cropped-fractional',f=>{f.crop=[2.5,3.75];f.scale=[.8,.75];f.sourceFrame=[1.25,4.5,72.75,66.5];f.plate=[12.5,17.25,41.75,34.25];});
for(let i=0;i<12;i++)make('margin-fringe-'+i,f=>{f.font=4+i;f.padding=[i/2+.5,i/4+1.5];f.verified=i%3===0;f.group=i%2===1;hole(f,7+i,6+i%4);hole(f,8+i,6+i%4);});
function attached(f){f.w=96;f.h=80;f.imageSize=[96,80];f.frame=[0,0,96,80];f.sourceFrame=f.frame;f.sourceBounds=[35/96,5/80,25/96,65/80];f.plate=[32,2,34,71];f.padding=[3,3];f.font=20;f.vertical=true;f.single=false;f.safe=Array(96*80).fill(1);for(let y=0;y<80;y++)hole(f,89,y);for(let y of [...Array.from({length:5},(_,i)=>20+i),...Array.from({length:5},(_,i)=>35+i)])for(let x=65;x<90;x++)hole(f,x,y);}
make('margin-attached-leading-veto',attached);make('margin-attached-chromatic-exempt',f=>{attached(f);f.verified=true;f.method='chromatic-balloon-glyphs';f.glyphsVerified=true;});make('margin-attached-chromatic-group-veto',f=>{attached(f);f.verified=true;f.method='chromatic-balloon-glyphs';f.glyphsVerified=true;f.group=true;});
for(const f of rows)f.expected=run(f);fs.writeFileSync(out,JSON.stringify(rows));console.log(rows.length+' frozen margin trials');
