#!/bin/bash
# Build the production native static library. The frozen browser/WASM oracle in
# AidokuTests is reference evidence and must not be regenerated by an app build.
set -euo pipefail
kernel_dir="$(cd "$(dirname "$0")" && pwd)"
exec python3 "$kernel_dir/native/build.py" "$@"
