// Generated by Scripts/overlay-kernels/native/generate-bindings.py. Kernel algorithms live only in kernels.rs.
import Foundation
import AidokuOverlayKernels

protocol NativeKernelElement: AdditiveArithmetic {}
extension UInt8: NativeKernelElement {}
extension Int32: NativeKernelElement {}
extension Float: NativeKernelElement {}
extension Double: NativeKernelElement {}

/// Zeroed, aligned scratch owned for the entire native call; pointers never escape this bridge.
final class NativeKernelBuffer<Element: NativeKernelElement> {
    let count: Int
    fileprivate let pointer: UnsafeMutablePointer<Element>
    private let retainedOwner: AnyObject?
    private let ownsStorage: Bool
    fileprivate var byteCount: Int { max(1, count) * MemoryLayout<Element>.stride }
    init(count: Int) throws {
        guard count >= 0, count <= (128 * 1_024 * 1_024) / MemoryLayout<Element>.stride else {
            throw NativeTranslationPixelKernels.KernelError.invalidBuffer
        }
        self.count = count
        retainedOwner = nil
        ownsStorage = true
        pointer = .allocate(capacity: max(1, count))
        pointer.initialize(repeating: .zero, count: max(1, count))
    }
    convenience init(values: [Element]) throws {
        try self.init(count: values.count)
        if !values.isEmpty { values.withUnsafeBufferPointer { pointer.update(from: $0.baseAddress!, count: values.count) } }
    }
    private init(pointer: UnsafeMutablePointer<Element>, count: Int, owner: AnyObject) {
        self.pointer = pointer; self.count = count; retainedOwner = owner; ownsStorage = false
    }
    /// Native kernels intentionally alias byte/Float32 scratch. The view retains its source allocation;
    /// offset, alignment and full byte extent are validated, and borrowed storage is never freed twice.
    func view<Other: NativeKernelElement>(as: Other.Type, byteOffset: Int, count: Int) throws -> NativeKernelBuffer<Other> {
        let capacity = self.count * MemoryLayout<Element>.stride
        guard byteOffset >= 0, byteOffset <= capacity, count >= 0,
              count <= (capacity - byteOffset) / MemoryLayout<Other>.stride else {
            throw NativeTranslationPixelKernels.KernelError.invalidBuffer
        }
        let bytes = UnsafeMutableRawPointer(pointer).advanced(by: byteOffset)
        guard UInt(bitPattern: bytes) % UInt(MemoryLayout<Other>.alignment) == 0 else {
            throw NativeTranslationPixelKernels.KernelError.invalidBuffer
        }
        return NativeKernelBuffer<Other>(pointer: bytes.assumingMemoryBound(to: Other.self), count: count, owner: self)
    }
    deinit { if ownsStorage { pointer.deinitialize(count: max(1, count)); pointer.deallocate() } }
    var values: [Element] { Array(UnsafeBufferPointer(start: pointer, count: count)) }
    subscript(index: Int) -> Element {
        get { precondition((0..<count).contains(index)); return pointer[index] }
        set { precondition((0..<count).contains(index)); pointer[index] = newValue }
    }
    fileprivate func require(_ minimum: Int) throws {
        guard minimum >= 0, count >= minimum else { throw NativeTranslationPixelKernels.KernelError.invalidBuffer }
    }
}

enum NativeTranslationPixelKernels {
    enum KernelError: Error { case invalidGeometry, invalidBuffer, invalidIndex, invalidScalar }
    static let exportedKernelCount = 25
    private static func checkedCount(_ value: Int32) throws -> Int {
        guard value >= 0, value <= 4_000_000 else { throw KernelError.invalidGeometry }
        return Int(value)
    }
    private static func pixelCount(_ width: Int32, _ height: Int32) throws -> Int {
        guard width > 0, height > 0, width <= 16_384, height <= 16_384,
              Int64(width) * Int64(height) <= 4_000_000 else { throw KernelError.invalidGeometry }
        return Int(width) * Int(height)
    }
    private static func indices(_ buffer: NativeKernelBuffer<Int32>, count: Int, pixels: Int) throws {
        try buffer.require(count)
        for index in 0..<count where buffer[index] < 0 || Int(buffer[index]) >= pixels { throw KernelError.invalidIndex }
    }
    private static func finite(_ buffer: NativeKernelBuffer<Double>, count: Int) throws {
        try buffer.require(count)
        for index in 0..<count where !buffer[index].isFinite { throw KernelError.invalidScalar }
    }

    static func lettering_rays(
        rgba: NativeKernelBuffer<UInt8>,
        dark: NativeKernelBuffer<UInt8>,
        w: Int32,
        h: Int32,
        x0: Int32,
        x1: Int32,
        y0: Int32,
        y1: Int32,
        out: NativeKernelBuffer<Int32>
    ) throws -> Int32 {
        let n = try pixelCount(w, h)
        try rgba.require(n*4)
        try dark.require(n)
        try out.require(n*4)
        guard x0 >= 0, x1 >= x0, x1 <= w, y0 >= 0, y1 >= y0, y1 <= h else { throw KernelError.invalidGeometry }
        let scratch: [AnyObject] = [rgba, dark, out]
        let byteCost = [rgba.byteCount, dark.byteCount, out.byteCount].reduce(0, +)
        guard byteCost <= 512 * 1_024 * 1_024 else { throw KernelError.invalidBuffer }
        return withExtendedLifetime(scratch) {
            AidokuOverlayKernels.lettering_rays(
                rgba.pointer,
                dark.pointer,
                w,
                h,
                x0,
                x1,
                y0,
                y1,
                out.pointer
            )
        }
    }

    static func lettering_support(
        rgba: NativeKernelBuffer<UInt8>,
        w: Int32,
        h: Int32,
        l: Double,
        r: Double,
        t: Double,
        b: Double,
        ir: Int32,
        ig: Int32,
        ib: Int32,
        out: NativeKernelBuffer<Int32>
    ) throws {
        let n = try pixelCount(w, h)
        guard l.isFinite else { throw KernelError.invalidScalar }
        guard r.isFinite else { throw KernelError.invalidScalar }
        guard t.isFinite else { throw KernelError.invalidScalar }
        guard b.isFinite else { throw KernelError.invalidScalar }
        guard ir >= 0, ir <= 255 else { throw KernelError.invalidScalar }
        guard ig >= 0, ig <= 255 else { throw KernelError.invalidScalar }
        guard ib >= 0, ib <= 255 else { throw KernelError.invalidScalar }
        try rgba.require(n*4)
        try out.require(4)
        let scratch: [AnyObject] = [rgba, out]
        let byteCost = [rgba.byteCount, out.byteCount].reduce(0, +)
        guard byteCost <= 512 * 1_024 * 1_024 else { throw KernelError.invalidBuffer }
        withExtendedLifetime(scratch) {
            AidokuOverlayKernels.lettering_support(
                rgba.pointer,
                w,
                h,
                l,
                r,
                t,
                b,
                ir,
                ig,
                ib,
                out.pointer
            )
        }
    }

    static func glyph_index(
        rgba: NativeKernelBuffer<UInt8>,
        n: Int32,
        start: NativeKernelBuffer<Int32>,
        order: NativeKernelBuffer<Int32>,
        cursor: NativeKernelBuffer<Int32>
    ) throws {
        let n = try checkedCount(n)
        try rgba.require(n*4)
        try start.require(4097)
        try order.require(n)
        try cursor.require(4096)
        let scratch: [AnyObject] = [rgba, start, order, cursor]
        let byteCost = [rgba.byteCount, start.byteCount, order.byteCount, cursor.byteCount].reduce(0, +)
        guard byteCost <= 512 * 1_024 * 1_024 else { throw KernelError.invalidBuffer }
        withExtendedLifetime(scratch) {
            AidokuOverlayKernels.glyph_index(
                rgba.pointer,
                Int32(n),
                start.pointer,
                order.pointer,
                cursor.pointer
            )
        }
    }

    static func glyph_seed(
        rgba: NativeKernelBuffer<UInt8>,
        w: Int32,
        h: Int32,
        cr: Int32,
        cg: Int32,
        cb: Int32,
        left: Double,
        right: Double,
        top: Double,
        bottom: Double,
        min_total: Double,
        vertical: Int32,
        origin: Double,
        span: Double,
        start: NativeKernelBuffer<Int32>,
        order: NativeKernelBuffer<Int32>,
        mask: NativeKernelBuffer<UInt8>,
        seen: NativeKernelBuffer<UInt8>,
        queue: NativeKernelBuffer<Int32>,
        core: NativeKernelBuffer<Int32>,
        stats: NativeKernelBuffer<Int32>
    ) throws -> Int32 {
        let n = try pixelCount(w, h)
        guard left.isFinite else { throw KernelError.invalidScalar }
        guard right.isFinite else { throw KernelError.invalidScalar }
        guard top.isFinite else { throw KernelError.invalidScalar }
        guard bottom.isFinite else { throw KernelError.invalidScalar }
        guard min_total.isFinite else { throw KernelError.invalidScalar }
        guard origin.isFinite else { throw KernelError.invalidScalar }
        guard span.isFinite else { throw KernelError.invalidScalar }
        guard cr >= 0, cr <= 255 else { throw KernelError.invalidScalar }
        guard cg >= 0, cg <= 255 else { throw KernelError.invalidScalar }
        guard cb >= 0, cb <= 255 else { throw KernelError.invalidScalar }
        try rgba.require(n*4)
        try start.require(4097)
        try order.require(n)
        try mask.require(n)
        try seen.require(n)
        try queue.require(n)
        try core.require(n)
        try stats.require(5)
        guard start[0] == 0, start[4096] <= n else { throw KernelError.invalidIndex }
        for index in 0..<4096 where start[index] < 0 || start[index] > start[index+1] { throw KernelError.invalidIndex }
        try indices(order, count: Int(start[4096]), pixels: n)
        let scratch: [AnyObject] = [rgba, start, order, mask, seen, queue, core, stats]
        let byteCost = [rgba.byteCount, start.byteCount, order.byteCount, mask.byteCount, seen.byteCount, queue.byteCount, core.byteCount,
            stats.byteCount].reduce(0, +)
        guard byteCost <= 512 * 1_024 * 1_024 else { throw KernelError.invalidBuffer }
        return withExtendedLifetime(scratch) {
            AidokuOverlayKernels.glyph_seed(
                rgba.pointer,
                w,
                h,
                cr,
                cg,
                cb,
                left,
                right,
                top,
                bottom,
                min_total,
                vertical,
                origin,
                span,
                start.pointer,
                order.pointer,
                mask.pointer,
                seen.pointer,
                queue.pointer,
                core.pointer,
                stats.pointer
            )
        }
    }

    static func glyph_enclosure(
        rgba: NativeKernelBuffer<UInt8>,
        w: Int32,
        h: Int32,
        core: NativeKernelBuffer<Int32>,
        len: Int32,
        stride: Int32,
        or: Int32,
        og: Int32,
        ob: Int32,
        out: NativeKernelBuffer<Int32>
    ) throws {
        let n = try pixelCount(w, h)
        guard or >= 0, or <= 255 else { throw KernelError.invalidScalar }
        guard og >= 0, og <= 255 else { throw KernelError.invalidScalar }
        guard ob >= 0, ob <= 255 else { throw KernelError.invalidScalar }
        try rgba.require(n*4)
        try core.require(Int(len))
        try out.require(2)
        guard len >= 0, stride > 0 else { throw KernelError.invalidScalar }
        try indices(core, count: Int(len), pixels: n)
        let scratch: [AnyObject] = [rgba, core, out]
        let byteCost = [rgba.byteCount, core.byteCount, out.byteCount].reduce(0, +)
        guard byteCost <= 512 * 1_024 * 1_024 else { throw KernelError.invalidBuffer }
        withExtendedLifetime(scratch) {
            AidokuOverlayKernels.glyph_enclosure(
                rgba.pointer,
                w,
                h,
                core.pointer,
                len,
                stride,
                or,
                og,
                ob,
                out.pointer
            )
        }
    }

    static func stroke_glyph(
        rgba: NativeKernelBuffer<UInt8>,
        w: Int32,
        h: Int32,
        fr: Int32,
        fg: Int32,
        fb: Int32,
        left: Double,
        right: Double,
        top: Double,
        bottom: Double,
        mask: NativeKernelBuffer<UInt8>,
        seen: NativeKernelBuffer<UInt8>,
        exterior: NativeKernelBuffer<UInt8>,
        queue: NativeKernelBuffer<Int32>,
        core: NativeKernelBuffer<Int32>,
        heights: NativeKernelBuffer<Int32>,
        out: NativeKernelBuffer<Int32>
    ) throws {
        let n = try pixelCount(w, h)
        guard left.isFinite else { throw KernelError.invalidScalar }
        guard right.isFinite else { throw KernelError.invalidScalar }
        guard top.isFinite else { throw KernelError.invalidScalar }
        guard bottom.isFinite else { throw KernelError.invalidScalar }
        guard fr >= 0, fr <= 255 else { throw KernelError.invalidScalar }
        guard fg >= 0, fg <= 255 else { throw KernelError.invalidScalar }
        guard fb >= 0, fb <= 255 else { throw KernelError.invalidScalar }
        try rgba.require(n*4)
        try mask.require(n)
        try seen.require(n)
        try exterior.require(n)
        try queue.require(n)
        try core.require(n)
        try heights.require(n)
        try out.require(2)
        let scratch: [AnyObject] = [rgba, mask, seen, exterior, queue, core, heights, out]
        let byteCost = [rgba.byteCount, mask.byteCount, seen.byteCount, exterior.byteCount, queue.byteCount, core.byteCount, heights.byteCount,
            out.byteCount].reduce(0, +)
        guard byteCost <= 512 * 1_024 * 1_024 else { throw KernelError.invalidBuffer }
        withExtendedLifetime(scratch) {
            AidokuOverlayKernels.stroke_glyph(
                rgba.pointer,
                w,
                h,
                fr,
                fg,
                fb,
                left,
                right,
                top,
                bottom,
                mask.pointer,
                seen.pointer,
                exterior.pointer,
                queue.pointer,
                core.pointer,
                heights.pointer,
                out.pointer
            )
        }
    }

    static func stroke_first(
        rgba: NativeKernelBuffer<UInt8>,
        w: Int32,
        h: Int32,
        core: NativeKernelBuffer<Int32>,
        len: Int32,
        stride: Int32,
        reach: Int32,
        fr: Int32,
        fg: Int32,
        fb: Int32,
        sx: NativeKernelBuffer<Int32>,
        sy: NativeKernelBuffer<Int32>,
        first: NativeKernelBuffer<Int32>
    ) throws -> Int32 {
        let n = try pixelCount(w, h)
        guard fr >= 0, fr <= 255 else { throw KernelError.invalidScalar }
        guard fg >= 0, fg <= 255 else { throw KernelError.invalidScalar }
        guard fb >= 0, fb <= 255 else { throw KernelError.invalidScalar }
        try rgba.require(n*4)
        try core.require(Int(len))
        try sx.require(Int(len))
        try sy.require(Int(len))
        try first.require(Int(len)*8)
        guard len >= 0, stride > 0 else { throw KernelError.invalidScalar }
        try indices(core, count: Int(len), pixels: n)
        guard reach > 0, reach <= 128 else { throw KernelError.invalidScalar }
        let scratch: [AnyObject] = [rgba, core, sx, sy, first]
        let byteCost = [rgba.byteCount, core.byteCount, sx.byteCount, sy.byteCount, first.byteCount].reduce(0, +)
        guard byteCost <= 512 * 1_024 * 1_024 else { throw KernelError.invalidBuffer }
        return withExtendedLifetime(scratch) {
            AidokuOverlayKernels.stroke_first(
                rgba.pointer,
                w,
                h,
                core.pointer,
                len,
                stride,
                reach,
                fr,
                fg,
                fb,
                sx.pointer,
                sy.pointer,
                first.pointer
            )
        }
    }

    static func stroke_seed(
        rgba: NativeKernelBuffer<UInt8>,
        w: Int32,
        h: Int32,
        samples: Int32,
        sx: NativeKernelBuffer<Int32>,
        sy: NativeKernelBuffer<Int32>,
        first: NativeKernelBuffer<Int32>,
        reach: Int32,
        fr: Int32,
        fg: Int32,
        fb: Int32,
        sr: Int32,
        sg: Int32,
        sb: Int32,
        rejoins: Int32,
        exterior: NativeKernelBuffer<UInt8>,
        bands: NativeKernelBuffer<Int32>,
        stats: NativeKernelBuffer<Int32>
    ) throws -> Int32 {
        let n = try pixelCount(w, h)
        guard fr >= 0, fr <= 255 else { throw KernelError.invalidScalar }
        guard fg >= 0, fg <= 255 else { throw KernelError.invalidScalar }
        guard fb >= 0, fb <= 255 else { throw KernelError.invalidScalar }
        guard sr >= 0, sr <= 255 else { throw KernelError.invalidScalar }
        guard sg >= 0, sg <= 255 else { throw KernelError.invalidScalar }
        guard sb >= 0, sb <= 255 else { throw KernelError.invalidScalar }
        try rgba.require(n*4)
        try sx.require(Int(samples))
        try sy.require(Int(samples))
        try first.require(Int(samples)*8)
        try exterior.require(n)
        try bands.require(Int(samples)*8)
        try stats.require(15)
        guard samples >= 0, samples <= n, reach > 0, reach <= 128 else { throw KernelError.invalidScalar }
        for index in 0..<Int(samples) where sx[index] < 0 || sx[index] >= w || sy[index] < 0 || sy[index] >= h { throw KernelError.invalidIndex }
        for index in 0..<(Int(samples)*8) where first[index] < 0 || first[index] > reach { throw KernelError.invalidIndex }
        let scratch: [AnyObject] = [rgba, sx, sy, first, exterior, bands, stats]
        let byteCost = [rgba.byteCount, sx.byteCount, sy.byteCount, first.byteCount, exterior.byteCount, bands.byteCount, stats.byteCount].reduce(0,
            +)
        guard byteCost <= 512 * 1_024 * 1_024 else { throw KernelError.invalidBuffer }
        return withExtendedLifetime(scratch) {
            AidokuOverlayKernels.stroke_seed(
                rgba.pointer,
                w,
                h,
                samples,
                sx.pointer,
                sy.pointer,
                first.pointer,
                reach,
                fr,
                fg,
                fb,
                sr,
                sg,
                sb,
                rejoins,
                exterior.pointer,
                bands.pointer,
                stats.pointer
            )
        }
    }

    static func bins_inside(
        rgba: NativeKernelBuffer<UInt8>,
        w: Int32,
        h: Int32,
        left: Double,
        right: Double,
        top: Double,
        bottom: Double,
        check_alpha: Int32,
        counts: NativeKernelBuffer<Int32>,
        sums: NativeKernelBuffer<Int32>,
        order: NativeKernelBuffer<Int32>
    ) throws -> Int32 {
        let n = try pixelCount(w, h)
        guard left.isFinite else { throw KernelError.invalidScalar }
        guard right.isFinite else { throw KernelError.invalidScalar }
        guard top.isFinite else { throw KernelError.invalidScalar }
        guard bottom.isFinite else { throw KernelError.invalidScalar }
        try rgba.require(n*4)
        try counts.require(4096)
        try sums.require(12288)
        try order.require(4096)
        let scratch: [AnyObject] = [rgba, counts, sums, order]
        let byteCost = [rgba.byteCount, counts.byteCount, sums.byteCount, order.byteCount].reduce(0, +)
        guard byteCost <= 512 * 1_024 * 1_024 else { throw KernelError.invalidBuffer }
        return withExtendedLifetime(scratch) {
            AidokuOverlayKernels.bins_inside(
                rgba.pointer,
                w,
                h,
                left,
                right,
                top,
                bottom,
                check_alpha,
                counts.pointer,
                sums.pointer,
                order.pointer
            )
        }
    }

    static func transpose_rgba(
        src: NativeKernelBuffer<UInt8>,
        dst: NativeKernelBuffer<UInt8>,
        w: Int32,
        h: Int32
    ) throws {
        let n = try pixelCount(w, h)
        try src.require(n*4)
        try dst.require(n*4)
        let scratch: [AnyObject] = [src, dst]
        let byteCost = [src.byteCount, dst.byteCount].reduce(0, +)
        guard byteCost <= 512 * 1_024 * 1_024 else { throw KernelError.invalidBuffer }
        withExtendedLifetime(scratch) {
            AidokuOverlayKernels.transpose_rgba(
                src.pointer,
                dst.pointer,
                w,
                h
            )
        }
    }

    static func outlined_components(
        rgba: NativeKernelBuffer<UInt8>,
        w: Int32,
        h: Int32,
        allow_dark: Int32,
        white: NativeKernelBuffer<UInt8>,
        seen: NativeKernelBuffer<UInt8>,
        queue: NativeKernelBuffer<Int32>,
        counts: NativeKernelBuffer<Int32>,
        sums: NativeKernelBuffer<Int32>,
        keys: NativeKernelBuffer<Int32>,
        out: NativeKernelBuffer<Int32>
    ) throws -> Int32 {
        let n = try pixelCount(w, h)
        try rgba.require(n*4)
        try white.require(n)
        try seen.require(n)
        try queue.require(n)
        try counts.require(4096)
        try sums.require(12288)
        try keys.require(4096)
        try out.require(n*9)
        let scratch: [AnyObject] = [rgba, white, seen, queue, counts, sums, keys, out]
        let byteCost = [rgba.byteCount, white.byteCount, seen.byteCount, queue.byteCount, counts.byteCount, sums.byteCount, keys.byteCount,
            out.byteCount].reduce(0, +)
        guard byteCost <= 512 * 1_024 * 1_024 else { throw KernelError.invalidBuffer }
        return withExtendedLifetime(scratch) {
            AidokuOverlayKernels.outlined_components(
                rgba.pointer,
                w,
                h,
                allow_dark,
                white.pointer,
                seen.pointer,
                queue.pointer,
                counts.pointer,
                sums.pointer,
                keys.pointer,
                out.pointer
            )
        }
    }

    static func caption_mask(
        rgba: NativeKernelBuffer<UInt8>,
        w: Int32,
        h: Int32,
        ir: Int32,
        ig: Int32,
        ib: Int32,
        tolerance: Int32,
        radius: Int32,
        il: Double,
        it: Double,
        iright: Double,
        ibottom: Double,
        dark_ink: Int32,
        interior_min: Double,
        near: NativeKernelBuffer<UInt8>,
        mask: NativeKernelBuffer<UInt8>,
        dots: NativeKernelBuffer<UInt8>,
        halo: NativeKernelBuffer<UInt8>,
        seen: NativeKernelBuffer<UInt8>,
        queue: NativeKernelBuffer<Int32>,
        stats: NativeKernelBuffer<Int32>
    ) throws -> Int32 {
        let n = try pixelCount(w, h)
        guard il.isFinite else { throw KernelError.invalidScalar }
        guard it.isFinite else { throw KernelError.invalidScalar }
        guard iright.isFinite else { throw KernelError.invalidScalar }
        guard ibottom.isFinite else { throw KernelError.invalidScalar }
        guard interior_min.isFinite else { throw KernelError.invalidScalar }
        guard ir >= 0, ir <= 255 else { throw KernelError.invalidScalar }
        guard ig >= 0, ig <= 255 else { throw KernelError.invalidScalar }
        guard ib >= 0, ib <= 255 else { throw KernelError.invalidScalar }
        try rgba.require(n*4)
        try near.require(n)
        try mask.require(n)
        try dots.require(n)
        try halo.require(n)
        try seen.require(n)
        try queue.require(n)
        try stats.require(4)
        guard radius >= 0, radius <= 128, tolerance >= 0, tolerance <= 255 else { throw KernelError.invalidScalar }
        let scratch: [AnyObject] = [rgba, near, mask, dots, halo, seen, queue, stats]
        let byteCost = [rgba.byteCount, near.byteCount, mask.byteCount, dots.byteCount, halo.byteCount, seen.byteCount, queue.byteCount,
            stats.byteCount].reduce(0, +)
        guard byteCost <= 512 * 1_024 * 1_024 else { throw KernelError.invalidBuffer }
        return withExtendedLifetime(scratch) {
            AidokuOverlayKernels.caption_mask(
                rgba.pointer,
                w,
                h,
                ir,
                ig,
                ib,
                tolerance,
                radius,
                il,
                it,
                iright,
                ibottom,
                dark_ink,
                interior_min,
                near.pointer,
                mask.pointer,
                dots.pointer,
                halo.pointer,
                seen.pointer,
                queue.pointer,
                stats.pointer
            )
        }
    }

    static func caption_periodic(
        dots: NativeKernelBuffer<UInt8>,
        w: Int32,
        h: Int32,
        axis: Int32
    ) throws -> Int32 {
        let n = try pixelCount(w, h)
        try dots.require(n)
        let scratch: [AnyObject] = [dots]
        let byteCost = [dots.byteCount].reduce(0, +)
        guard byteCost <= 512 * 1_024 * 1_024 else { throw KernelError.invalidBuffer }
        return withExtendedLifetime(scratch) {
            AidokuOverlayKernels.caption_periodic(
                dots.pointer,
                w,
                h,
                axis
            )
        }
    }

    static func caption_exposed(
        rgba: NativeKernelBuffer<UInt8>,
        w: Int32,
        mask: NativeKernelBuffer<UInt8>,
        halo: NativeKernelBuffer<UInt8>,
        textured: Int32,
        x0: Int32,
        x1: Int32,
        y0: Int32,
        y1: Int32,
        vertical: Int32,
        start: Double,
        length: Double,
        r: NativeKernelBuffer<UInt8>,
        g: NativeKernelBuffer<UInt8>,
        b: NativeKernelBuffer<UInt8>,
        band: NativeKernelBuffer<UInt8>,
        stats: NativeKernelBuffer<Int32>
    ) throws {
        guard w > 0, rgba.count % (Int(w)*4) == 0 else { throw KernelError.invalidGeometry }
        let n = try pixelCount(w, Int32(rgba.count / (Int(w)*4)))
        guard start.isFinite else { throw KernelError.invalidScalar }
        guard length.isFinite else { throw KernelError.invalidScalar }
        try rgba.require(n*4)
        try mask.require(n)
        try halo.require(n)
        try r.require(n)
        try g.require(n)
        try b.require(n)
        try band.require(n)
        try stats.require(3)
        guard x0 >= 0, x1 >= x0, x1 <= w, y0 >= 0, y1 >= y0, y1 <= Int32(n / Int(w)) else { throw KernelError.invalidGeometry }
        guard length > 0 else { throw KernelError.invalidScalar }
        let scratch: [AnyObject] = [rgba, mask, halo, r, g, b, band, stats]
        let byteCost = [rgba.byteCount, mask.byteCount, halo.byteCount, r.byteCount, g.byteCount, b.byteCount, band.byteCount,
            stats.byteCount].reduce(0, +)
        guard byteCost <= 512 * 1_024 * 1_024 else { throw KernelError.invalidBuffer }
        withExtendedLifetime(scratch) {
            AidokuOverlayKernels.caption_exposed(
                rgba.pointer,
                w,
                mask.pointer,
                halo.pointer,
                textured,
                x0,
                x1,
                y0,
                y1,
                vertical,
                start,
                length,
                r.pointer,
                g.pointer,
                b.pointer,
                band.pointer,
                stats.pointer
            )
        }
    }

    static func columns_sort(
        r: NativeKernelBuffer<UInt8>,
        g: NativeKernelBuffer<UInt8>,
        b: NativeKernelBuffer<UInt8>,
        band: NativeKernelBuffer<UInt8>,
        count: Int32,
        ro: NativeKernelBuffer<UInt8>,
        go: NativeKernelBuffer<UInt8>,
        bo: NativeKernelBuffer<UInt8>,
        bando: NativeKernelBuffer<UInt8>,
        offsets: NativeKernelBuffer<Int32>
    ) throws {
        let n = try checkedCount(count)
        try r.require(n)
        try g.require(n)
        try b.require(n)
        try band.require(n)
        try ro.require(n)
        try go.require(n)
        try bo.require(n)
        try bando.require(n)
        try offsets.require(767)
        let scratch: [AnyObject] = [r, g, b, band, ro, go, bo, bando, offsets]
        let byteCost = [r.byteCount, g.byteCount, b.byteCount, band.byteCount, ro.byteCount, go.byteCount, bo.byteCount, bando.byteCount,
            offsets.byteCount].reduce(0, +)
        guard byteCost <= 512 * 1_024 * 1_024 else { throw KernelError.invalidBuffer }
        withExtendedLifetime(scratch) {
            AidokuOverlayKernels.columns_sort(
                r.pointer,
                g.pointer,
                b.pointer,
                band.pointer,
                count,
                ro.pointer,
                go.pointer,
                bo.pointer,
                bando.pointer,
                offsets.pointer
            )
        }
    }

    static func columns_bins(
        r: NativeKernelBuffer<UInt8>,
        g: NativeKernelBuffer<UInt8>,
        b: NativeKernelBuffer<UInt8>,
        count: Int32,
        counts: NativeKernelBuffer<Int32>,
        sums: NativeKernelBuffer<Int32>,
        order: NativeKernelBuffer<Int32>
    ) throws -> Int32 {
        let n = try checkedCount(count)
        try r.require(n)
        try g.require(n)
        try b.require(n)
        try counts.require(4096)
        try sums.require(12288)
        try order.require(4096)
        let scratch: [AnyObject] = [r, g, b, counts, sums, order]
        let byteCost = [r.byteCount, g.byteCount, b.byteCount, counts.byteCount, sums.byteCount, order.byteCount].reduce(0, +)
        guard byteCost <= 512 * 1_024 * 1_024 else { throw KernelError.invalidBuffer }
        return withExtendedLifetime(scratch) {
            AidokuOverlayKernels.columns_bins(
                r.pointer,
                g.pointer,
                b.pointer,
                count,
                counts.pointer,
                sums.pointer,
                order.pointer
            )
        }
    }

    static func columns_support(
        r: NativeKernelBuffer<UInt8>,
        g: NativeKernelBuffer<UInt8>,
        b: NativeKernelBuffer<UInt8>,
        count: Int32,
        m0: Double,
        m1: Double,
        m2: Double,
        out: NativeKernelBuffer<Int32>
    ) throws {
        let n = try checkedCount(count)
        guard m0.isFinite else { throw KernelError.invalidScalar }
        guard m1.isFinite else { throw KernelError.invalidScalar }
        guard m2.isFinite else { throw KernelError.invalidScalar }
        try r.require(n)
        try g.require(n)
        try b.require(n)
        try out.require(4)
        let scratch: [AnyObject] = [r, g, b, out]
        let byteCost = [r.byteCount, g.byteCount, b.byteCount, out.byteCount].reduce(0, +)
        guard byteCost <= 512 * 1_024 * 1_024 else { throw KernelError.invalidBuffer }
        withExtendedLifetime(scratch) {
            AidokuOverlayKernels.columns_support(
                r.pointer,
                g.pointer,
                b.pointer,
                count,
                m0,
                m1,
                m2,
                out.pointer
            )
        }
    }

    static func columns_range(
        r: NativeKernelBuffer<UInt8>,
        g: NativeKernelBuffer<UInt8>,
        b: NativeKernelBuffer<UInt8>,
        count: Int32,
        hist: NativeKernelBuffer<Int32>
    ) throws -> Int32 {
        let n = try checkedCount(count)
        try r.require(n)
        try g.require(n)
        try b.require(n)
        try hist.require(256)
        let scratch: [AnyObject] = [r, g, b, hist]
        let byteCost = [r.byteCount, g.byteCount, b.byteCount, hist.byteCount].reduce(0, +)
        guard byteCost <= 512 * 1_024 * 1_024 else { throw KernelError.invalidBuffer }
        return withExtendedLifetime(scratch) {
            AidokuOverlayKernels.columns_range(
                r.pointer,
                g.pointer,
                b.pointer,
                count,
                hist.pointer
            )
        }
    }

    static func columns_brighter(
        r: NativeKernelBuffer<UInt8>,
        g: NativeKernelBuffer<UInt8>,
        b: NativeKernelBuffer<UInt8>,
        band: NativeKernelBuffer<UInt8>,
        count: Int32,
        m0: Double,
        m1: Double,
        m2: Double,
        out: NativeKernelBuffer<Int32>
    ) throws {
        let n = try checkedCount(count)
        guard m0.isFinite else { throw KernelError.invalidScalar }
        guard m1.isFinite else { throw KernelError.invalidScalar }
        guard m2.isFinite else { throw KernelError.invalidScalar }
        try r.require(n)
        try g.require(n)
        try b.require(n)
        try band.require(n)
        try out.require(2)
        let scratch: [AnyObject] = [r, g, b, band, out]
        let byteCost = [r.byteCount, g.byteCount, b.byteCount, band.byteCount, out.byteCount].reduce(0, +)
        guard byteCost <= 512 * 1_024 * 1_024 else { throw KernelError.invalidBuffer }
        withExtendedLifetime(scratch) {
            AidokuOverlayKernels.columns_brighter(
                r.pointer,
                g.pointer,
                b.pointer,
                band.pointer,
                count,
                m0,
                m1,
                m2,
                out.pointer
            )
        }
    }

    static func columns_sum(
        r: NativeKernelBuffer<UInt8>,
        g: NativeKernelBuffer<UInt8>,
        b: NativeKernelBuffer<UInt8>,
        from: Int32,
        to: Int32,
        out: NativeKernelBuffer<Int32>
    ) throws {
        guard from >= 0, to >= from else { throw KernelError.invalidGeometry }
        let n = try checkedCount(to)
        try r.require(n)
        try g.require(n)
        try b.require(n)
        try out.require(3)
        let scratch: [AnyObject] = [r, g, b, out]
        let byteCost = [r.byteCount, g.byteCount, b.byteCount, out.byteCount].reduce(0, +)
        guard byteCost <= 512 * 1_024 * 1_024 else { throw KernelError.invalidBuffer }
        withExtendedLifetime(scratch) {
            AidokuOverlayKernels.columns_sum(
                r.pointer,
                g.pointer,
                b.pointer,
                from,
                to,
                out.pointer
            )
        }
    }

    static func harmonic_fill(
        p: NativeKernelBuffer<UInt8>,
        w: Int32,
        n: Int32,
        queue: NativeKernelBuffer<Int32>,
        tail: Int32,
        blocked: NativeKernelBuffer<UInt8>,
        paint: NativeKernelBuffer<UInt8>,
        accelerated: Int32,
        work: NativeKernelBuffer<Float>,
        links: NativeKernelBuffer<UInt8>
    ) throws {
        let n = try checkedCount(n)
        try p.require(n*4)
        try queue.require(Int(tail))
        try blocked.require(n)
        try paint.require(n)
        try work.require(n*3)
        try links.require(Int(tail))
        guard w > 2, n % Int(w) == 0, n / Int(w) > 2, tail >= 0, tail <= n else { throw KernelError.invalidGeometry }
        try indices(queue, count: Int(tail), pixels: n)
        for index in 0..<Int(tail) { let pixel = Int(queue[index]); guard pixel % Int(w) > 0, pixel % Int(w) < Int(w)-1, pixel >= Int(w),
            pixel < n-Int(w) else { throw KernelError.invalidIndex } }
        let scratch: [AnyObject] = [p, queue, blocked, paint, work, links]
        let byteCost = [p.byteCount, queue.byteCount, blocked.byteCount, paint.byteCount, work.byteCount, links.byteCount].reduce(0, +)
        guard byteCost <= 512 * 1_024 * 1_024 else { throw KernelError.invalidBuffer }
        withExtendedLifetime(scratch) {
            AidokuOverlayKernels.harmonic_fill(
                p.pointer,
                w,
                Int32(n),
                queue.pointer,
                tail,
                blocked.pointer,
                paint.pointer,
                accelerated,
                work.pointer,
                links.pointer
            )
        }
    }

    static func exemplar_fill(
        rgba: NativeKernelBuffer<UInt8>,
        w: Int32,
        h: Int32,
        mask: NativeKernelBuffer<UInt8>,
        forbidden: NativeKernelBuffer<UInt8>,
        fg: NativeKernelBuffer<Double>,
        coeff: NativeKernelBuffer<Double>,
        erased: Int32,
        work: NativeKernelBuffer<UInt8>,
        pending: NativeKernelBuffer<UInt8>,
        residual: NativeKernelBuffer<Float>,
        filled: NativeKernelBuffer<Float>,
        integral: NativeKernelBuffer<Int32>,
        output: NativeKernelBuffer<UInt8>,
        donors: NativeKernelBuffer<Int32>,
        cell: NativeKernelBuffer<Double>,
        grid_x: NativeKernelBuffer<Int32>,
        grid_y: NativeKernelBuffer<Int32>,
        stats: NativeKernelBuffer<Double>
    ) throws -> Int32 {
        let n = try pixelCount(w, h)
        try rgba.require(n*4)
        try mask.require(n)
        try forbidden.require(n)
        try fg.require(3)
        try coeff.require(9)
        try work.require(n*4)
        try pending.require(n)
        try residual.require(n*3)
        try filled.require(n*3)
        try integral.require((Int(w)+1)*(Int(h)+1))
        try output.require(n*4)
        try donors.require(n)
        try cell.require(n)
        try grid_x.require(Int(w))
        try grid_y.require(Int(h))
        try stats.require(7)
        guard erased >= 0, erased <= n else { throw KernelError.invalidScalar }
        try finite(fg, count: 3); try finite(coeff, count: 9)
        let scratch: [AnyObject] = [rgba, mask, forbidden, fg, coeff, work, pending, residual, filled, integral, output, donors, cell, grid_x, grid_y,
            stats]
        let byteCost = [rgba.byteCount, mask.byteCount, forbidden.byteCount, fg.byteCount, coeff.byteCount, work.byteCount, pending.byteCount,
            residual.byteCount, filled.byteCount, integral.byteCount, output.byteCount, donors.byteCount, cell.byteCount, grid_x.byteCount,
            grid_y.byteCount, stats.byteCount].reduce(0, +)
        guard byteCost <= 512 * 1_024 * 1_024 else { throw KernelError.invalidBuffer }
        return withExtendedLifetime(scratch) {
            AidokuOverlayKernels.exemplar_fill(
                rgba.pointer,
                w,
                h,
                mask.pointer,
                forbidden.pointer,
                fg.pointer,
                coeff.pointer,
                erased,
                work.pointer,
                pending.pointer,
                residual.pointer,
                filled.pointer,
                integral.pointer,
                output.pointer,
                donors.pointer,
                cell.pointer,
                grid_x.pointer,
                grid_y.pointer,
                stats.pointer
            )
        }
    }

    static func enclosed_paper(
        rgba: NativeKernelBuffer<UInt8>,
        w: Int32,
        h: Int32,
        l: Int32,
        t: Int32,
        r: Int32,
        bottom: Int32,
        rects: NativeKernelBuffer<Double>,
        aux_n: Int32,
        exc_n: Int32,
        paper: NativeKernelBuffer<UInt8>,
        seen: NativeKernelBuffer<UInt8>,
        q: NativeKernelBuffer<Int32>,
        best: NativeKernelBuffer<Int32>,
        region: NativeKernelBuffer<UInt8>,
        outside: NativeKernelBuffer<UInt8>,
        points: NativeKernelBuffer<Int32>,
        meta: NativeKernelBuffer<Int32>,
        output: NativeKernelBuffer<UInt8>,
        safe: NativeKernelBuffer<UInt8>,
        stats: NativeKernelBuffer<Int32>
    ) throws -> Int32 {
        let n = try pixelCount(w, h)
        try rgba.require(n*4)
        try rects.require((Int(aux_n)+Int(exc_n))*4)
        try paper.require(n)
        try seen.require(n)
        try q.require(n)
        try best.require(n)
        try region.require(n)
        try outside.require(n)
        try points.require(n)
        try meta.require(n*2)
        try output.require(n*4)
        try safe.require(n)
        try stats.require(3)
        guard aux_n >= 0, exc_n >= 0, aux_n <= 4096, exc_n <= 4096, l >= 0, t >= 0, r >= l, r <= w, bottom >= t,
            bottom <= h else { throw KernelError.invalidGeometry }
        try finite(rects, count: (Int(aux_n)+Int(exc_n))*4)
        let scratch: [AnyObject] = [rgba, rects, paper, seen, q, best, region, outside, points, meta, output, safe, stats]
        let byteCost = [rgba.byteCount, rects.byteCount, paper.byteCount, seen.byteCount, q.byteCount, best.byteCount, region.byteCount,
            outside.byteCount, points.byteCount, meta.byteCount, output.byteCount, safe.byteCount, stats.byteCount].reduce(0, +)
        guard byteCost <= 512 * 1_024 * 1_024 else { throw KernelError.invalidBuffer }
        return withExtendedLifetime(scratch) {
            AidokuOverlayKernels.enclosed_paper(
                rgba.pointer,
                w,
                h,
                l,
                t,
                r,
                bottom,
                rects.pointer,
                aux_n,
                exc_n,
                paper.pointer,
                seen.pointer,
                q.pointer,
                best.pointer,
                region.pointer,
                outside.pointer,
                points.pointer,
                meta.pointer,
                output.pointer,
                safe.pointer,
                stats.pointer
            )
        }
    }

    static func local_components(
        rgba: NativeKernelBuffer<UInt8>,
        w: Int32,
        h: Int32,
        l: Int32,
        t: Int32,
        right: Int32,
        bottom: Int32,
        bg: NativeKernelBuffer<Double>,
        bmax: Double,
        excluded: NativeKernelBuffer<UInt8>,
        ink: NativeKernelBuffer<UInt8>,
        seen: NativeKernelBuffer<UInt8>,
        safe: NativeKernelBuffer<UInt8>,
        q: NativeKernelBuffer<Int32>,
        paint: NativeKernelBuffer<UInt8>,
        member: NativeKernelBuffer<UInt8>,
        output: NativeKernelBuffer<UInt8>,
        parts: NativeKernelBuffer<Int32>,
        part_capacity: Int32,
        points: NativeKernelBuffer<Int32>,
        stats: NativeKernelBuffer<Int32>
    ) throws -> Int32 {
        let n = try pixelCount(w, h)
        guard bmax.isFinite else { throw KernelError.invalidScalar }
        try rgba.require(n*4)
        try bg.require(3)
        try excluded.require(n)
        try ink.require(n)
        try seen.require(n)
        try safe.require(n)
        try q.require(n)
        try paint.require(n)
        try member.require(n)
        try output.require(n*4)
        try parts.require(Int(part_capacity)*8)
        try points.require(n)
        try stats.require(4)
        guard part_capacity >= 0, part_capacity <= n, l >= 0, t >= 0, right >= l, right <= w, bottom >= t,
            bottom <= h else { throw KernelError.invalidGeometry }
        try finite(bg, count: 3)
        let scratch: [AnyObject] = [rgba, bg, excluded, ink, seen, safe, q, paint, member, output, parts, points, stats]
        let byteCost = [rgba.byteCount, bg.byteCount, excluded.byteCount, ink.byteCount, seen.byteCount, safe.byteCount, q.byteCount, paint.byteCount,
            member.byteCount, output.byteCount, parts.byteCount, points.byteCount, stats.byteCount].reduce(0, +)
        guard byteCost <= 512 * 1_024 * 1_024 else { throw KernelError.invalidBuffer }
        return withExtendedLifetime(scratch) {
            AidokuOverlayKernels.local_components(
                rgba.pointer,
                w,
                h,
                l,
                t,
                right,
                bottom,
                bg.pointer,
                bmax,
                excluded.pointer,
                ink.pointer,
                seen.pointer,
                safe.pointer,
                q.pointer,
                paint.pointer,
                member.pointer,
                output.pointer,
                parts.pointer,
                part_capacity,
                points.pointer,
                stats.pointer
            )
        }
    }

    static func pixel_classes(
        rgba: NativeKernelBuffer<UInt8>,
        n: Int32,
        colors: NativeKernelBuffer<Double>,
        flags: Int32,
        ink_tolerance: Double,
        halo_separation: Double,
        raw: NativeKernelBuffer<UInt8>,
        observed: NativeKernelBuffer<UInt8>,
        protected: NativeKernelBuffer<UInt8>
    ) throws {
        let n = try checkedCount(n)
        guard ink_tolerance.isFinite else { throw KernelError.invalidScalar }
        guard halo_separation.isFinite else { throw KernelError.invalidScalar }
        try rgba.require(n*4)
        try colors.require(12)
        try raw.require(n)
        try observed.require(n)
        try protected.require(n)
        try finite(colors, count: 12)
        let scratch: [AnyObject] = [rgba, colors, raw, observed, protected]
        let byteCost = [rgba.byteCount, colors.byteCount, raw.byteCount, observed.byteCount, protected.byteCount].reduce(0, +)
        guard byteCost <= 512 * 1_024 * 1_024 else { throw KernelError.invalidBuffer }
        withExtendedLifetime(scratch) {
            AidokuOverlayKernels.pixel_classes(
                rgba.pointer,
                Int32(n),
                colors.pointer,
                flags,
                ink_tolerance,
                halo_separation,
                raw.pointer,
                observed.pointer,
                protected.pointer
            )
        }
    }

}
