#!/usr/bin/env python3
"""Audit native stage references without treating a helper declaration as execution."""
import datetime,hashlib,json,re
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];DIR=Path(__file__).parent
OVERLAY=ROOT/'Aidoku/Core/Translation/NativeEngine/Overlay'
sources={p.name:p.read_text() for p in OVERLAY.glob('*.swift')}
renderer=sources['NativeTranslationRenderer.swift'];start=renderer.index('static func renderSynchronously(')
end=renderer.index('static func initialSlantedTypography(',start)
body=renderer[start:end]
stageNames=['prepare','refining','growPlateTypography','reconcileDisplayStyleCohorts','reconcilePolarityLegibility','preserveLetteringPolarity','prepareSourcePanels','applySourceStyles','polishPanelGeometry','oversizedTitleGloss','packCaptions','preparePrimaryOutlines','effectGloss','polishFinalGeometry','polishCaptionPanels','reconcileFinalStrokes','separateCaptions','applySourcePosition','prepareFinalTrials','commitBalloonUnits','applyLightLettering','releaseCertifiedPlates','containBalloonText','apply','adjustInitialJoinedUnits','applyCaptionFixedBoxReflow','applySlantedTrials','reconcileTypographyHarmony','fitLatePageEdges','applySourceAlignment','minimalRestoredPlates','containJoinedBalloonUnits','splitBalloonUnitParts','holdLateReadableFloor','clipLateBalloonPanels','centerLateBalloonBodies','restoreSourceFrameLines','liftFinalRotatedReadability','repairKoreanStacks','restoreDisplayLettering','applyLetteringUnitPalette','applyDisplayGroups','applyLatePlateTrim','linkFinalPlates','applyGlyphCover','recoverLines']
trace=[]
for m in re.finditer(r'(?:(Native\w+)\.)?('+('|'.join(stageNames))+r')\s*\(',body):
 line=renderer[:start+m.start()].count('\n')+1
 trace.append(dict(order=len(trace)+1,symbol=(m.group(1)+'.' if m.group(1) else 'NativeTranslationRenderer.')+m.group(2),file='NativeTranslationRenderer.swift',line=line,statement=renderer.splitlines()[line-1].strip()))
def calls(symbol):
 out=[]
 for file,source in sources.items():
  pattern = re.escape(symbol)+r'\s*\('
  owner,method=symbol.rsplit('.',1)
  aliases=re.findall(r'\btypealias\s+(\w+)\s*=\s*'+re.escape(owner)+r'\b',source)
  candidates=[re.escape(symbol)]+[re.escape(alias+'.'+method) for alias in aliases]
  if owner=='NativeTranslationRenderer' and ('extension NativeTranslationRenderer' in source or file=='NativeTranslationRenderer.swift'):
   candidates.append(r'\b'+re.escape(method))
  pattern='(?:'+'|'.join(candidates)+r')\s*\('
  if symbol == 'NativeDeferredForcedRestoration.apply': pattern = r'\bdeferred\.apply\s*\('
  if symbol == 'NativeBalloonInteriorEstimator.estimate': pattern = r'\bestimator\.estimate\s*\('
  for m in re.finditer(pattern,source):
   if re.search(r'func\s+$',source[max(0,m.start()-12):m.start()]):continue
   out.append(dict(file=file,line=source[:m.start()].count('\n')+1))
 return out
stages=[
 dict(stage='Plate growth and post-growth cohorts',legacyLines=[7953,8871],condition='opacity==1 && items.length<=256; actual visible readability plate after font clustering, then all plate growers followed by restored-surface growers',native=['NativeTranslationRenderer.growPlateTypography','NativeTypographyPlateGrowth.grow','NativeTypographyPlateGrowth.flatRoom','NativeTypographyPlateGrowth.reconcile','NativeTypographyDisplayWidening.widen','NativeTypographyRotatedGrowth.grow'],status='production-callbacks-chronology-partial',proof=['build/native-plate-growth-host/report.json','build/native-plate-growth-host/cohort-report.json','build/native-plate-growth-host/flat-report.json','build/native-display-widening-host/report.json','build/native-rotated-growth-host/report.json','build/native-render-parity/plate-growth-scroll-adapter/report.json'],limitations=['250 full axis-growPlate fixtures,151 live cohort fixtures and72 exact native-pixel room fixtures prove pure policies. The real Card/physical Range/CoreText/source-pixel callback extension is now called after caption packing.','Rotated-body/display and growPlateWide now have actual Card callbacks:290 frozen rotated policies with101accepted decisions and239 widening policies with83accepted decisions match numeric geometry at1e-9. Scalar Range row unions, Canvas metrics and source pixel band reads are production inputs; All three real growth callbacks now consume shared integer ContentFitMetrics from actual candidate font/pitch/scale/pads. Seven actual Card/CoreText growth regressions pass; stored raw/reset and restored-session block-word style follows committed child state; vertical-only nil fallback is explicit. Shared CSS assigned-width provenance and platform metrics still require final image verification.','BUILD29 independently decoded final PNGs:7/16 exact,9different,2,141,026 differing pixels. Growth diagnostics preserve entering/leaving geometry; real7card10 huge panel exists before growth. Real15card9 andreal7card14 still overgrow. Production phase split is initial cohorts beforeCard, plate collection then restored growth then combined cohorts, harmony afterwards; owner element usedLayoutUnit quantization and later caption reflow fixes require a new runtime comparison.']),
 dict(stage='Final page display-style majority cohorts',legacyLines=[13874,14103],condition='opacity==1 && preserveSourceTextColor && preserveSourceBackgroundColor && items.length<=256; immutable pre-pass style/ring/backing collection after polarity polish',native=['NativeDisplayStyleCohort.decisions','NativeDisplayStyleCohort.backing','NativeTranslationRenderer.reconcileDisplayStyleCohorts'],status='production-reference-present-metadata-pending',proof=['build/native-display-style-cohort-host/report.json','build/native-display-style-cohort-host/backing-report.json'],limitations=['Full unchanged frozen majority-style block355/355 conditions,104committed decisions numeric1e-9. Original Uint8/fractional luminance raster110/110 exact arrays,geometry,budgets,percentiles and overlapping panels.','Both new pure helper and actual Card adapter are published. The actual adapter consumes Card.sourceBackgroundKind/sourceStrokeKind metadata, locks committed displayLetteringRecord, and writesstrokeKind=none onstroke removal. Unknown metadata remains explicit inunclassifiedIDs. Completeness of all preceding metadata mutations and600kbacking range transport remains an independent chronology obligation.']),
 dict(stage='Initial observed restoration and joined-unit mask',legacyLines=[1714,1789],condition='opacity==1 && inpaintingEnabled; joined unit and undetached crop',native=['NativeTranslationRestoration.prepare','NativeRestorationPixels.restore','NativeTranslationRestoration.clipUnitInterior'],status='partially-integrated',proof=['build/verify-restoration-latest-independent/observed41-diff.json'],limitations=['Direct observed and undetached spatial41 outputs exact; entire per-page crop/cache/shared budget order not certified.','Native clipUnitInterior is called for abs(rotation)<.01; frozen condition uses !detached. Joined-unit bookkeeping and actual final unit layout require separate audit.']),
 dict(stage='Slanted restoration search with actual typography',legacyLines=[2800,3350],condition='opacity==1 && inpaintingEnabled && rotated source',native=['NativeSlantedRestoration.restore','NativeSlantedTypographyTrial.run','NativeSlantedTypographyTrial.upright','NativeTranslationRenderer.applySlantedTrials'],status='production-search-chronology-partial',proof=['build/verify-restoration-latest-independent/slanted-diff.json','build/native-render-parity/slanted-typography/report.json','build/native-render-parity/slanted-adapter/report.json'],limitations=['242 restoration buffers and137 deterministic full frozen typography-search policies match.2host tests invoke actual CoreText and production SlantedContext admissions, commit and clip with real source proof rasters.','Production prepare callbacks now call SlantedContext.admit/admitPage and preserve speculative layouts for applyInitial; later applySlantedTrials invokes live search. The old initialSlantedInkFits glyphBounds helpers remain declared but are not the current callback entry.','Full search/source palette chronology and platform Range/Canvas raster equivalence remain subject to the final zero-difference PNG gate.']),
 dict(stage='Initial balloon clear-region expanded surface grid',legacyLines=[4749,4837],condition='fitBalloon clearSearch; original safe crop<=262144;64px plane-certified exterior only beforelate; connected erased source core',native=['NativeEarlyBalloonGrid.build'],status='helper-proved-production-adapter-pending',proof=['build/native-early-balloon-grid-host/report.json'],limitations=['113full unchanged frozen grid fixtures with111positive outputs compare exactblocked/reachedbytes andInt32SAT SHA256, clearqueries andsourcepixel exterior crop reads; geometry1e-9.','Production helper is published; actual EarlyBalloon search owner must transport genuine restoration canvas alpha, source plane, interior mask and shared-budget probes. No source pixels or canvas-alpha provenance are inferred from an image placeholder.']),
 dict(stage='Balloon interior provider',legacyLines=[6270,6453],condition='opacity==1; joined/native contour then topology fallback',native=['NativeBalloonRelayout.nativeUnitInterior','NativeBalloonInteriorEstimator.estimate'],status='production-provider-chronology-partial',proof=['build/native-render-parity/balloon-interior-policy.json'],limitations=['16 source topology/crop/page budget fixtures; actual BalloonRelayoutContext.interior supplies nativeUnitInterior then estimator.estimate with sampled source image and bounded per-page cache. Whole provider query order/caller chronology remains unproved by helper fixtures.']),
 dict(stage='Late short-caption and balloon restoration trials',legacyLines=[9300,9806],condition='remaining readability plate; owned surface/proposal; fit eligible; shared late search budget',native=['NativeFinalRestorationTrial.shortCaption','NativeFinalRestorationTrial.balloonSafeFit'],status='production-trial-chronology-partial',proof=['build/verify-restoration-latest-independent/trial56/report.json'],limitations=['56 exact buffers/admission/undo/callback chronology with supplied glyph rectangles and DOM parenting transport.','Production prepareFinalTrials directly invokes balloonSafeFit before alignment and shortCaption after effect gloss, using live candidate/proposal and finalRestorationFit CoreText hooks.56 supplied-geometry proofs and app adapter tests do not establish exact platform shaping/chronology.']),
 dict(stage='Joined-unit containment, splitting and plated contour reflow',legacyLines=[10819,11760],condition='opacity==1 && items.length<=256; joined unit without residue/rotation/vertical; actual owner and contour',native=['NativeBalloonRelayout.relayout','NativeJoinedUnitContainment.contain','NativeBalloonUnitParts.place','NativeTranslationRenderer.containJoinedBalloonUnits','NativeTranslationRenderer.splitBalloonUnitParts'],status='partial',proof=['build/native-render-parity/balloon-relayout-policy.json'],limitations=['Live containJoinedBalloonUnits and splitBalloonUnitParts are invoked after finalContrast/minimalRestoredPlates with actual BalloonRelayoutContext;40containment policies exact. Exact source-unit state/owner ordering and physical shaper/crop chronology remain distinct obligations.']),
 dict(stage='Deferred final source-owned force pass',legacyLines=[16159,16277],condition='opacity==1 && inpaintingEnabled && complete source image; only extant non-erasure readability/rotated panels',native=['NativeDeferredForcedRestoration.apply','NativeResidualProof.forceComponent','NativeForcedSourceInpainting.restore'],status='production-final-force-chronology-partial',proof=['build/verify-restoration-latest-independent/forced45-actual/report.json'],limitations=['45 actual palette/helper outcomes exact; final panel existence admission and independent 6M page budget are caller obligations.','SourceInk segmentation metadata now preserves its own channels/outline/confidence without display fallback; four actual segmentation/metadata regressions pass, while real25 same-buffer cause attribution awaits the bounded runtime capture. Actual renderSynchronously invokes deferred.apply after final short-caption trial and before releaseCertifiedPlates, using surviving owned readability panel plus gloss hidden/removal gates. Partial/rotated admission equivalence and shared page budget chronology remain separate from the45 helper outcomes.']),
 dict(stage='Final release and polish',legacyLines=[16279,16400],condition='certified connected nonprovisional erasure; vertical/partial/foreign-owner gates followed by final geometry/panels/outline/clusters/separation',native=['NativeTranslationRenderer.reconcileFinalStrokes','NativeBalloonTextContainment.contain','NativePanelGeometry.containBalloonPanels','NativeTranslationCaptionPanelPolish.polish','NativeTranslationCaptionSeparation.separateLines','NativeTranslationCaptionSeparation.separateColumns'],status='partial-final-chronology',proof=['build/native-render-parity/final-geometry-policy.json','build/native-source-style-host/differential.json'],limitations=['67 final geometry/containment cases and lower styles/outline/geometry passes do not prove exact caller ordering.','Native actual trace is recorded separately below; typography/plate mutation snapshots and final paint are strict PNG gate.'])
]
# Keep direct references distinct from dynamic closure transport and local methods.
for stage in stages:
 stage['directNativeReferences']={symbol:calls(symbol) for symbol in stage['native']}
 stage['reviewRequired']=True
 if stage['status']=='helper-verified-adapter-pending' and any(stage['directNativeReferences'].values()):
  stage['status']='production-reference-present-chronology-partial'
  stage['limitations'].append('Current native references are recorded above; callback state/chronology and real glyph transport remain separate from reference presence.')
x=dict(generatedAtUTC=datetime.datetime.now(datetime.timezone.utc).isoformat(),method='Read-only qualified native reference and top-level stage trace. Manual frozen conditional seam audit; no reachability inference from declarations, no image pass inferred.',wholeChronologyExact=False,sourceSHA256={name:hashlib.sha256(source.encode()).hexdigest() for name,source in sources.items() if name in ['NativeTranslationRenderer.swift','NativeTranslationRestoration.swift','NativeDeferredForcedRestoration.swift','NativeFinalRestorationTrial.swift','NativeRestorationUnitInterior.swift']},actualNativeTopLevelOrder=trace,conditionalStages=stages,finalImageGate='ReaderTranslationNativePixelParityTests requires zero differing RGBA pixels; no relaxation for kernel/helper success.')
(DIR/'render-chronology.json').write_text(json.dumps(x,indent=2)+'\n')
print(json.dumps(dict(nativeStageCalls=len(trace),conditionalStages=len(stages),wholeChronologyExact=False)))
