#!/usr/bin/env python3
"""Snapshot manual semantic audit of frozen render-body stages against actual native callers."""
import hashlib,json,re
from collections import Counter
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];O=ROOT/'Aidoku/Core/Translation/NativeEngine/Overlay';REF=ROOT/'Scripts/native-render-parity/reference-source';OUT=ROOT/'build/native-render-parity/whole-stage-audit.json'
# Anchors are immutable frozen-source lines, not mutable production line numbers.
# Existing helper presence is deliberately not an integration verdict.
rows=[
(995,1188,'render root/session, kept source descriptors, image/crop cache','transport',['NativeTranslationRenderer.swift','NativeSourceColorSamplingStage.swift','NativeKeptSourceRestoration.swift'],'Native renderer typed descriptors and native reader; WebKit root/session globals replaced by overlay revision/cancellation. Canvas raster proof46 and straight repair transport40 are independent; no final-image equality implied.'),
(1189,1268,'conditional coordinated source columns','integrated',['NativeTranslationLayout.swift'],'NativeTranslationLayoutPlanner.refining inspects original image before conditional columnLayout commit; shared Swift planner remains. Native prepare sees resulting geometry.'),
(1269,1349,'page restoration budgets and reduced safe/luminance surface pools','integrated',['NativeTranslationSurfacePool.swift','NativeTypographyPostPolish.swift'],'PostPolish Context calls native pooled surface probes, masks and luminance retained by actual restoration. Budget/geometry table differences still require end-to-end result comparison.'),
(1350,1568,'slanted restoration, upright alternatives, pending source-readable lift state','in_progress',['NativeSlantedTypographyTrial.swift','NativeTranslationRenderer.swift'],'Pure slanted trial exists. Root assigned integration author actual run/lift/clip wrappers; at snapshot no NativeSlantedTypographyTrial.run call yet. Initial actual renderer only initialSlantedInkFits/initialPageSlantedInkFits supplied to restoration.'),
(1569,1906,'joined unit source masks, observed/ordinary restoration descriptor assembly','integrated',['NativeTranslationRestoration.swift','NativeRestorationUnitInterior.swift','NativeSpatialSourceCrop.swift'],'prepare assembles original/aux/excluded polygons and unit interior, retains proof/candidate metadata, rather than treating union as source ink.'),
(1907,1908,'initial source restoration attachment','integrated',['NativeTranslationRestoration.swift'],'NativeTranslationRenderer calls prepare with slanted admission callbacks before card shaping.'),
(1909,1966,'joined unit largest native interior rectangle before initial type','partial',['NativeTranslationLayout.swift','NativeRestorationUnitInterior.swift'],'Native planner initial balloon/native unit layout exists; exact anonymous largest-interior fallback and unitResidueRisk chronology needs explicit adapter evidence, not later BalloonUnitCommit.'),
(1967,2132,'emergency/surface/word/slanted/balloon budgets and bound paragraph admission helpers','partial',['NativeTypographyPostPolish.swift','NativeFinalRestorationTrial.swift'],'Context implements separate budgets and surface/readable growers; source phase ordering differs, see growth row. Trial residual budget/callback proof does not establish all original layout measurements.'),
(2133,2285,'source stroke-weight/serif detection, registered source face','integrated',['NativeRestorationLetterStyles.swift','NativeRestorationLetterStyle.swift','NativeTranslationTypography.swift'],'Actual restoration sampleLetterStyles/resolvedLetterStyles and actual CoreText registered bundled serif used to build style. Platform font shaping/image parity remains failing.'),
(2286,2327,'heavy source lettering helper definition','integrated',['NativeTranslationRenderer.swift'],'Actual final card heavyStrokeWidth computes absolute and page-relative weighting, suppressed on applied outline. Source helper declaration itself does not run until15717.'),
(2328,2378,'one-step serif evidence propagation and font-ready continuation','integrated',['NativeRestorationLetterStyles.swift','NativeTranslationTypography.swift'],'Actual resolvedLetterStyles spreads one-step source serif evidence; CoreText registration replaces font-loading continuation.'),
(2379,6147,'initial node creation, Korean fit/word/punctuation reflow, restored glyph fitting and typography entries','partial',['NativeTranslationLayout.swift','NativeTranslationTypography.swift','NativeTypographyPostPolish.swift','NativeKoreanInlineRepair.swift'],'Typed planner.refining and actual Card fitting are invoked; NativeKoreanInlineRepair called from layout. CoreText range/DOM scroll substitution, upfront post-polish and slanted acceptance chronology are material limits; no whole-block exact claim.'),
(6148,6547,'balloon interior estimation and relayout callbacks','in_progress',['NativeBalloonInteriorEstimator.swift','NativeBalloonRelayout.swift','NativeTranslationRenderer+BalloonRelayout.swift'],'Estimator and relayout pure helpers have frozen proofs; compositor now owns actual extension. Declaration-only helpers not counted as actual stage until caller inserted.'),
(6548,6609,'separate final readability plates and transparent text reflow','integrated',['NativeTranslationRenderer.swift'],'Actual prepareReadabilityPanels uses observed source palette and source erasure/glyph/margin proof, keeps geometry and source panels separately.'),
(6610,6617,'artwork-first smaller type after normal Korean reflow','partial',['NativeTypographyPostPolish.swift','NativeTranslationLayout.swift'],'Native artwork source constraints exist, but explicit same protectArtwork late typography-entry stage/order not demonstrated.'),
(6618,6648,'initial final-observed ink clustering','integrated',['NativeTranslationSourceStylePostPolish.swift','NativeTranslationRenderer.swift'],'applySourceStyles(stage:.initialInk) calls resolve on actual cards after prepareReadabilityPanels.'),
(6649,6716,'source anchor + protected text backing','integrated',['NativePanelGeometry.swift','NativeTranslationRenderer.swift'],'Actual polishPanelGeometry invokes sourceAnchorShift + needsTextBacking on frozen panel snapshots.'),
(6717,7176,'observed mainbody margin certification, source-position outlined release and residual fit','partial',['NativeRendererSourcePosition.swift','NativePartialSourceProof.swift','NativeFinalRestorationTrial.swift','NativeTranslationRenderer.swift'],'applySourcePosition and marginProof actual calls exist; source-mask conditional initial/group margin has31fixture proof. Exact early fitBalloon(false,true) placement separate from late trial is not shown.'),
(7177,7265,'early compact panel source/fringe preservation and visible-surface contrast','integrated',['NativePanelGeometry.swift','NativeTranslationRenderer.swift'],'NativePanelGeometry.polish native actual call covers early compactPanel + foreign source fringe, backing and contrast. This is NOT late14350 pixel-aware source-side trim.'),
(7266,7271,'detached local proposal commit or canvas removal','partial',['NativeRestorationCandidate.swift','NativeTranslationRenderer.swift'],'Actual provisional candidate and late commit/undo supported; exact early detached proposal removal before oversized title pass not separately represented. Native immutable initial patch remains visible unless candidate gates remove it.'),
(7272,7419,'oversized failed-restoration title/gloss','integrated',['NativeTranslationOversizedTitleGloss.swift','NativeTranslationRenderer.swift'],'Actual oversizedTitleGloss(cards:) consumes current panels/restoration and returns hidden ids/placement; independent pure policy proof exists.'),
(7420,7893,'opaque-caption unified rectangle partition/foreign-fill commit','integrated',['NativeCaptionPacking.swift','NativeTranslationRenderer.swift'],'Actual packCaptions after oversizedTitleGloss invokes pack with native shaper/source reader and commits panel/backing/foreignfill geometry.'),
(7894,9734,'restored/plated source-size growth, cohort harmony, row/interface/word/readability passes','order_mismatch',['NativeTypographyPostPolish.swift','NativeTypographyPlateGrowth.swift','NativeTranslationRenderer.swift'],'Renderer still invokes PostPolish.refining before Card creation/readability and pack; frozen this whole main stage follows committed plates. Author confirmed added after-pack axis grow/session does not move original restored collection/cohort. Pure algorithm presence is not exact chronology.'),
(9735,9807,'late balloon safe-fit optional specks/residual repair trial','integrated',['NativeFinalRestorationTrial.swift','NativeTranslationRenderer.swift'],'Actual prepareFinalTrials(balloonStage:true) runs after pack, before alignment; exact56late trial plus31margin pure proofs and actual iOS trial suite5 pass. Whole-layout callback/native font fit is separate.'),
(9808,9853,'page-edge shifted or shrunken glyphs preserving owner plate','partial',['NativeTypographyPostPolish.swift','NativeTranslationFinalGeometry.swift'],'Actual code (not stale half-line comment) moves only free text by <=font*1.2, excludes plated shifts/manual resizing, decreases font by0.5 to min(font,7), accepts overflow<0.75, and restores unresolved font/lineheight. No neighbor, scroll or line-count guard. Root owns new exact adapter.'),
(9854,10382,'source paragraph left alignment and line topology','integrated',['NativeTranslationSourceAlignment.swift','NativeTranslationRenderer+SourceAlignment.swift','NativeTranslationRenderer.swift'],'Actual applySourceAlignment after late trial, before BalloonUnitCommit; original source reader + line offsets persisted through remeasureTypography.'),
(10383,10542,'complete erasure balloon unit stack at one size','integrated',['NativeTranslationBalloonUnitCommit.swift','NativeTranslationRenderer.swift'],'Actual commitBalloonUnits invoked after alignment on actual cards/restoration. Distinct from late10815 joined source-union containment/parts.'),
(10543,10682,'final actual-owner source contrast and final ink cohorts','integrated',['NativeTranslationSourceStylePostPolish.swift','NativeTranslationRenderer.swift'],'Actual applySourceStyles(.finalContrast) invoked after BalloonUnitCommit. Native resolve finalContrast is not later majority cohort13874.'),
(10683,10814,'minimal-area restored plate original-clean-surface trim','in_progress',['NativeMinimalRestoredPlate.swift','NativeTranslationRenderer+MinimalPlates.swift'],'Pure exact native helper and actual extension authored by restoration agent; no top-level minimalRestoredPlates call at audit snapshot. Distinct14350 pixel-side trim.'),
(10815,10952,'late joined unit line containment, possible shrink and coverage growth','missing',['NativeTranslationBalloonUnitCommit.swift','NativeBalloonTextContainment.swift'],'Earlier stack commit and final named balloon containment do not implement this whole word-bound search + partial source gate + exact rollback stage. Root assigns compositor next.'),
(10953,11071,'joined two-member text-part split search at larger size','missing',['BrowserOverlayBalloonUnitLayout.swift'],'Native source member planning/per-member stack does not implement late joined paragraph split into two text spans after containment. Root assigns layout author next.'),
(11072,11095,'plate-free final readable-floor8.5 hold with unchanged line count','missing',['NativeTypographyPostPolish.swift'],'No exact late root-only inpainted glyph 7.75..8.5 lift/linecount/neighbor rollback pass. Upfront growing is different. Root implementing next.'),
(11096,11185,'sampled balloon paper contour pixel-run clipping while retaining required foreign ink','missing',['NativePanelGeometry.swift','NativeBalloonInteriorEstimator.swift'],'Final named containBalloonPanels contour policy16382 is distinct. No earlier sampled-estimator-fill rowrun/coverage original caller found. Root implementing next.'),
(11186,11233,'verified native balloon BODY-centre text-only shift','missing',['NativeTranslationBalloonUnitCommit.swift','NativePanelGeometry.swift'],'Earlier sourceAnchor and unit stacking do not implement this final native lobe centre shift with exact measured neighbor/owner preflight. Root implementing next.'),
(11234,11350,'source straight frame/rule repaint in owner background','in_progress',['NativeSourceFrameLines.swift','NativeTranslationRenderer+SourceFrameLines.swift','NativeTranslationRenderer.swift'],'Root authored helper+adapter; actual try restoreSourceFrameLines before Primary. Published owner CGImage/count consumed GlyphCover; chronology earlier missing preceding unit/clip/body stages remains.'),
(11351,11570,'late failed-restoration opaque rotated-plate readable floor','missing',['NativeSlantedTypographyTrial.swift'],'Early restored-surface pending lift is semantically distinct. No late opaque owner9/8.75/8.5 width/paper/color polygon clearance original pass; root assigned integration author next.'),
(11571,11593,'detach rotated background plate under lettering','transport',['NativeTranslationRenderer.swift'],'Native draw preserves separate rotated sourcePanels/card paint phases. Conditional frame/order affects subsequent policy; no DOM clone required.'),
(11594,11964,'late stack/column/fragment/joined-unit split repair on composited page surfaces','missing',['NativeKoreanInlineRepair.swift','NativeTypographyPostPolish.swift'],'NativeKoreanInlineRepair is early two ratio probes + punctuation inset, not original two-round6000layout/393216pixel composited source + transparent clone topology trial.'),
(11965,12106,'conditional actual glyph point paint-order lifts with owner veto','missing',['NativeTranslationRenderer.swift'],'All panels before text is not conditional per-owner DOM z/coverage/contrast/higher-caption veto. Root assigns compositor phase/paint next. Accepted GlyphCover owner live order tracked separately.'),
(12107,13077,'saturated/BW display lettering artwork erasure and source display style','missing',['NativeRestorationChromatic.swift','NativeConnectedLettering.swift','NativePrimaryOutlinedLettering.swift'],'No anonymous displayMask or BW self-similarity-donor diffusion/component split/ambiguous/invented/residual pass, nor actual full display orchestration. Source chromatic balloon and completeConnectedLettering are different algorithms.'),
(13078,13098,'plate/rotated-quad geometry helpers','integrated',['NativePanelGeometry.swift','NativeTranslationRenderer.swift'],'panelMeetsInk/rotatedBounds actual callbacks supply geometry for subsequent observed outline decisions.'),
(13099,13757,'native-scale outlined fill/outline role scan + primary action','integrated',['NativeSourceOutlineEvidence.swift','NativeSourceOutlineScan.swift','NativePrimaryOutlinedLettering.swift','NativeTranslationRenderer.swift'],'Actual preparePrimaryOutlines scans and commits current owner/observed role decisions. Display replacement stage preceding it is missing, so whole initial-state equality cannot be claimed.'),
(13758,13873,'polarity-preserving owner plate hue tone','in_progress',['NativeTranslationSourceStylePostPolish.swift'],'No existing CIE Lab bounded chromaticity hue-tone policy; root owns new complete pass now. FinalContrast/adjustInk is semantically different.'),
(13874,14103,'majority source display-style cohorts on actual composited backing','in_progress',['NativeTranslationSourceStylePostPolish.swift'],'No current 600k actual backing2..98 percentile+majority role pass. Root assigns parity author; existing initial/final swatch clustering is different.'),
(14104,14222,'one plate colour per same lettering unit','in_progress',['NativeLetteringUnitPalette.swift'],'Pure port written by export author; actual separate stage adapter pending. Genuine provenance required.'),
(14223,14349,'adjacent slanted display column grouping','in_progress',['NativeTranslationRenderer.swift'],'Card.displayGroup genuine marker now declared, actual grouping stage assigned layout author; helper declaration/empty marker is not coverage.'),
(14350,14596,'late pixel-aware source-side/fringe plate trim','missing',['NativePanelGeometry.swift'],'Early compactPanel cannot replace this full sourceSides perwantedband original source pixel probe + grow/trim owner/backing/caption coverage policy. Parent now assigns this agent after audit.'),
(14597,14903,'final plate-to-lettering linkage and parent geometry commit','missing',['NativeTranslationCaptionPanelPolish.swift'],'Final named aidokuPolishCaptionPanels16375 is different. Parent assigns export author complete anonymous plate linkage next.'),
(14904,15484,'glyph-shaped smooth artwork repair, exact masks/diffusion/edges/AA','integrated',['NativeGlyphCover.swift','NativeTranslationRenderer+GlyphCover.swift','NativeTranslationRenderer.swift'],'Actual applyGlyphCover after Primary before Light;20/20 complete frozen proof9success including rotated/clipped/robust curves. Card owner patch marker + generic export mask preserved; compositor fixes live insertion order. Prior missing phases still block whole-page equality.'),
(15485,15496,'widened display-card clip extends under protruding current glyph ink','missing',['NativeTranslationRenderer.swift'],'Card.displayCardGrowth provenance now exists; no exact afterGlyphCover coverage extension invocation to retain free-surface widened ink found.'),
(15497,15716,'light source lettering topology roles/owner palette preservation','integrated',['NativeLightLettering.swift','NativeTranslationRenderer.swift'],'Actual applyLightLettering after GlyphCover, genuine glyphCoverRecord avoids owner-dependent branch; pure source policy137exact per root report.'),
(15717,15718,'apply heavy source lettering at final display size','order_mismatch',['NativeTranslationRenderer.swift'],'Native heavyStrokeWidth actual assignment after final caption separation, whereas frozen applies before effectGloss/recovered/force/release. Final stroke suppression helps but cached original page stroke weighting/peer order could differ.'),
(15719,15726,'budget diagnostics and rotated plate layer order','transport',['NativeTranslationRenderer.swift'],'Native diagnostics collected from actual card/candidate; bitmap/PDF layering differs by live versus export. No WebKit budget diagnostics requirement for paint identity.'),
(15727,16017,'effect/logo gloss preserving unerased original source','integrated',['NativeTranslationEffectGloss.swift','NativeTranslationRenderer.swift'],'Actual effectGloss on current cards/readSource; returns hidden/removed IDs, notes, source zones. GlyphCover export masks and live owned paint must follow removed IDs.'),
(16018,16091,'recovered-line native-source protected overlay probes','integrated',['NativeRecoveredLineProtection.swift','NativeTranslationRenderer+RecoveredLines.swift','NativeTranslationRenderer.swift'],'Actual recoverLines produces recovered layers after effects. Original text/page/protection source pixel probes invoked through separate adapter.'),
(16092,16154,'short caption outline release after optional enclosed specks + actual unsafe-glyph gate','integrated',['NativeFinalRestorationTrial.swift','NativeTranslationRenderer.swift'],'Actual prepareFinalTrials(balloonStage:false) before forced fallback; frozen exact late56fixture proof+app5test suite. No generic unconditional fillSpecks mutation.'),
(16155,16269,'late remaining-owner bounded forced-source inpaint and old proof replacement','integrated',['NativeDeferredForcedRestoration.swift','NativeForcedSourceInpainting.swift','NativeForcedComponentRestoration.swift','NativeTranslationRenderer.swift'],'Actual deferredForced.apply only after actual owner gate, full metadata/quality null palette preserved.45/45 force proof, native candidate chronology app tests; app image transport straight-alpha fixed40/40.'),
(16270,16363,'certified glyph-only plate release with native column/narrow outline handling','integrated',['NativeTranslationRenderer.swift','NativeTranslationSourceStylePostPolish.swift'],'Actual releaseCertifiedPlates before final geometry; preserves source physical fill/stroke. Refuses uncertified/provisional/partial mainbody.'),
(16364,16372,'upright final caption text/plate policies','integrated',['NativeTranslationFinalGeometry.swift','NativeTranslationRenderer.swift'],'Actual polishFinalGeometry(anchorsOnly:false) invokes uprightText/uprightPlate after release.'),
(16373,16385,'final named caption panels, balloon contain, vertical anchors','integrated',['NativeTranslationCaptionPanelPolish.swift','NativeBalloonTextContainment.swift','NativePanelGeometry.swift','NativeTranslationRenderer.swift'],'Actual polishCaptionPanels, containBalloonText, containBalloonPanels and anchorsOnly:true invoke these separately and in original late order; not counted as anonymous late-trim/unit stages.'),
(16386,16392,'observed dark-outline style and clustered stroke + line/column separation','integrated',['NativeTranslationSourceStylePostPolish.swift','NativeTranslationCaptionSeparation.swift','NativeTranslationRenderer.swift'],'Actual reconcileFinalStrokes then separateCaptions before kept-source overlays. Independent final helper proofs exist.'),
(16393,16471,'kept original source reconstruction and final image clip','integrated',['NativeKeptSourceRestoration.swift','NativeTranslationRenderer.swift'],'Actual sourceRestorationRects derives final glyphs+panels+patches+effectzones, source image copied above overlay in bitmap and extracted/PDF split. Whole decoded image strict baseline still failing.'),
]
# Reviewed actual renderer chronology at the later integration snapshot. These
# are semantic adapter verdicts, not an automatic matching-name promotion.
updates = {
1350: ('integrated',['NativeSlantedTypographyTrial.swift','NativeTranslationRenderer+SlantedTrials.swift','NativeTranslationRenderer.swift'],'Actual applySlantedTrials invokes pending slanted trial, commits accepted item/style/panel geometry and stores clipping metadata. Initial preparation has native source glyph admission callbacks; final platform range equivalence remains separately gated.'),
1909: ('in_progress',['NativeTranslationLayout.swift','NativeRestorationUnitInterior.swift','NativeTranslationRenderer.swift'],'Exact post-restoration/residue largest consecutive balloon-band rectangle stage is missing at this snapshot; root now owns new pre-initial-card adapter. Raster unit interior and original planner balloon layout do not implement it.'),
6148: ('integrated',['NativeBalloonInteriorEstimator.swift','NativeBalloonRelayout.swift','NativeTranslationRenderer+BalloonRelayout.swift','NativeTranslationRenderer.swift'],'Actual BalloonRelayoutContext initialized before packCaptions and supplied to the native fit/reflow callbacks; actual glyph measurements drive candidate/rollback. Typed policies use original reader and cached interior.'),
6717: ('partial',['NativeRendererSourcePosition.swift','NativePartialSourceProof.swift','NativeFinalRestorationTrial.swift','NativeTranslationRenderer.swift'],'Only direct margin predicate in prepareSourcePanels and outlinedSourcePosition action exist. Full source group/exterior priority, three-pass partial fit, enlarged paper candidate and remaining residual fit orchestration absent; this agent now owns separate EarlyMargin implementation. Actual source-position action precedes sourceAnchor/compact instead of following anchor; see earlyMarginSubStages.'),
10683: ('integrated',['NativeMinimalRestoredPlate.swift','NativeTranslationRenderer+MinimalPlates.swift','NativeTranslationRenderer.swift'],'Actual minimalRestoredPlates called after finalContrast and before late unit/geometry stages. Full native minimal plate policy/source clean surface proof; distinct from pixel-aware final trim.'),
11072: ('integrated',['NativeLateBalloonStages.swift','NativeTranslationRenderer+LateBalloonStages.swift','NativeTranslationRenderer.swift'],'Actual holdLateReadableFloor after minimalRestoredPlates; bounded floor trial measures range/line count and neighbor clearance, commits only accepted font/lineheight.'),
11096: ('integrated',['NativeLateBalloonStages.swift','NativeTranslationRenderer+LateBalloonStages.swift','NativeTranslationRenderer.swift'],'Actual clipLateBalloonPanels uses sampled balloon context native rowrun mask/paper proof and preserves required own/foreign glyph coverage; distinct from final containBalloonPanels.'),
11186: ('integrated',['NativeLateBalloonStages.swift','NativeTranslationRenderer+LateBalloonStages.swift','NativeTranslationRenderer.swift'],'Actual centerLateBalloonBodies follows sampled clips before SourceFrameLines, uses native balloon BODY center and measured owner/neighbor veto; no item or panel mutation beyond accepted text shift.'),
11234: ('integrated',['NativeSourceFrameLines.swift','NativeTranslationRenderer+SourceFrameLines.swift','NativeTranslationRenderer.swift'],'Actual restoreSourceFrameLines after late body center before Primary. Real owner sourceFrameImage/sourceFrameLineCount provenance vetoes GlyphCover and future owner-dependent passes.'),
13758: ('integrated',['NativePolarityLegibility.swift','NativeTranslationRenderer+Polarity.swift','NativeTranslationRenderer.swift'],'Actual preserveLetteringPolarity after Primary before majority cohorts. Complete bounded hue/tone/polarity helper consumes current owner and native source sample; original finalContrast is a separate earlier pass.'),
13874: ('integrated',['NativeDisplayStyleCohort.swift','NativeTranslationRenderer+DisplayStyleCohort.swift','NativeTranslationRenderer.swift'],'Actual reconcileDisplayStyleCohorts after polarity before LetteringUnitPalette, uses actual backing/surface evidence and sourceBackgroundKind/sourceStrokeKind metadata. Native measured surface and WebKit composited-surface pixel equality remains separate.'),
14104: ('integrated',['NativeLetteringUnitPalette.swift','NativeTranslationRenderer+LetteringUnitPalette.swift','NativeTranslationRenderer.swift'],'Actual applyLetteringUnitPalette after display cohorts before DisplayGroups; typed stage reconciles accepted owners, sampled ink and actual foreign fills.'),
14223: ('integrated',['NativeTranslationDisplayGroups.swift','NativeTranslationRenderer+DisplayGroups.swift','NativeTranslationRenderer.swift'],'Actual applyDisplayGroups after LetteringUnitPalette before LatePlateTrim, consumes measured source column topology and publishes real Card.displayGroup metadata. GlyphCover observes genuine grouping state.'),
14350: ('integrated',['NativeLatePlateTrim.swift','NativeTranslationRenderer+LatePlateTrim.swift','NativeTranslationRenderer.swift'],'Actual applyLatePlateTrim after DisplayGroups before FinalPlateLinkage;40/40 frozen whole-block fixtures24positive, exact source band reads/budget/geometry/coverage/art-veto/rollback. Native adapter only changes panel geometry; actual app3test suite awaits root simulator run.'),
14597: ('integrated',['NativeFinalPlateLinkage.swift','NativeTranslationRenderer+FinalPlateLinkage.swift','NativeTranslationRenderer.swift'],'Actual linkFinalPlates follows pixel trim before GlyphCover; complete anonymous pure stage with caption owner geometry commit/rollback and pixel/source clearance. Distinct final named CaptionPanelPolish.'),
14904: ('integrated',['NativeGlyphCover.swift','NativeTranslationRenderer+GlyphCover.swift','NativeTranslationRenderer.swift'],'Actual applyGlyphCover after final linkage before Light;20/20 frozen9positive. Accepted patch retained both generic export mask and Card.glyphCoverPatch; LIVE renderer filters owned image from early mask paint and draws it immediately before owner panel/text, PDF retains extracted mask order. Actual app3test suite root BUILD28 executing.'),
}
rows=[(a,b,stage,*updates[a]) if a in updates else (a,b,stage,status,files,reason) for a,b,stage,status,files,reason in rows]
def snapshot(name):
 p=O/name
 if not p.exists():return dict(file=name,exists=False)
 text=p.read_text();return dict(file=name,exists=True,sha256=hashlib.sha256(p.read_bytes()).hexdigest(),calls=[dict(line=i+1,text=line.strip()) for i,line in enumerate(text.splitlines()) if re.search(r'Native[A-Za-z0-9_]+\.[A-Za-z0-9_]+\(',line)][:130])
renderer=(O/'NativeTranslationRenderer.swift').read_text()
chronology=[dict(line=i+1,text=line.strip()) for i,line in enumerate(renderer.splitlines()) if 180<=i<=360 and re.match(r'(?:try )?(?:[a-z][A-Za-z]+\(|let \w+ = [a-z][A-Za-z]+\()',line.strip())]
subStages=[dict(start=a,end=b,stage=c,status=d) for a,b,c,d in [(6736,6792,'disconnected exterior residual flood helper','missing'),(6794,6846,'direct source-margin classification and candidate queue','partial'),(6847,6911,'opaque four-pixel bilinear group source proof and revision','missing'),(6912,6932,'leftover artwork budget exterior priority','missing'),(6933,6942,'full certified three-mode fitBalloon trials','missing'),(6943,7000,'mainbody/large partial topology helper declarations','integrated'),(7001,7054,'three-pass partial fit priority and proof rollback','missing'),(7055,7100,'larger96px enclosed-paper temporary candidate rollback','missing'),(7102,7155,'source-position outlined release','order_mismatch'),(7157,7176,'remaining residual completion then complete fit trial','missing')]]
table=[dict(order=i+1,frozen=dict(file='BrowserOverlayView.swift',start=a,end=b),stage=stage,status=status,nativeFiles=files,evidence=reason) for i,(a,b,stage,status,files,reason) in enumerate(rows)]
# Every body line belongs to one ordered row, including declarations/transports.
assert all(rows[i][1]+1==rows[i+1][0] for i in range(len(rows)-1))
report=dict(scope='Every line995–16471 of unchanged frozen BrowserOverlayView render-body, grouped by complete top-level semantic stage; inner restoration/typography library declarations covered only with actual callsite qualifications. Existing pure helper or matching name does not imply high-level integration/equivalent chronology. Snapshot while original eight authors integrate pending stages.',sourceSHA256=hashlib.sha256((REF/'BrowserOverlayView.swift').read_bytes()).hexdigest(),coverage=dict(start=995,end=16471,contiguous=True,stages=len(rows)),statusCounts=dict(Counter(r['status'] for r in table)),allOriginalStagesImplemented=False,finalDecodedImageIdentical=False,rows=table,earlyMarginSubStages=subStages,rendererChronology=chronology,nativeSnapshot=[snapshot(name) for name in sorted({f for r in rows for f in r[4]})])
OUT.parent.mkdir(parents=True,exist_ok=True);OUT.write_text(json.dumps(report,indent=2));print(OUT,report['statusCounts'])
